### ISSUE TITLE
standardize linter config across repos

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#100]
# Bounty

We want to enforce code style across all the repos and have something to reference for new contributors.

## Scope

- create a blueprint config for linting Javascript code. Should be based on our existing practices as much as possible. Reuse existing configs (e.g. airbnb) as much as possible.
- create a blueprint config for linting Solidity code. Should be based on our existing practices as much as possible. Reuse existing configs (e.g. open zeppelin) as much as possible.
- reuse linter config across repos. Consider publishing our config to npm, so that it is easier to keep up with the changes.
- update https://github.com/leapdao/meta/blob/master/CONTRIBUTION.md with information about code conventions (reference configs)

## Deliverables

- npm packages with linter config?
- npm package with solidity config?

## Gain for the project

- easier to collaborate on a same codebase
- easier to onboard new contributors

## Roles
bounty gardener: @troggy / 40 DAI flat
bounty worker: @troggy / 80%
bounty reviewer: name / 20%

## Funded by

Dev Circle

**Comment by troggy** [comment]
@sunify @TimDaub @vrde what do you think is the best way to have a shared linter config for multiple repos? 

I see at least the following options: 
- have it as an npm module. PROS: harder to create overrides. CONS: When style guide changes you have to bump version in all the repos.
- use git modules to reference the config from a single place. PROS: no need to update repos when style guide changes. Harder to create overrides. CONS: ugly
- copy-paste and manually update from a single well-known place. PROS: already doing something similar. CONS: When style guide changes you have to update all the repos. Easy to create overrides.

**Comment by troggy** [comment]
Proposed setup for JS:
- eslint-config-airbnb-base
- prettier + eslint-config-prettier
- eslint-plugin-prettier

**Comment by troggy** [comment]
Proposed setup for Solidity:
- solhint
