### ISSUE TITLE
create paper-wallet generator (customize for sticker + template)

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#101]
# Bounty

## Scope
- adjust script
- incorporate sunDAI template
- customize for stickers

## Deliverables
- printed + funded wallets at DAOcon

## Gain for the project
- deliver successful showcase

## Roles
bounty gardener: @eshavkun  / 10%
bounty worker: @eshavkun  / 85%
bounty reviewer: name / 15%

**Comment by eshavkun** [comment]
Script:
https://github.com/leapdao/paper-wallet/commit/a94d1aa5d5c4af27c74679e8476d7734ace2de24
Paper wallets were printed and delivered on conference

**Comment by johannbarbie** [comment]
delivered and payed out.
