### ISSUE TITLE
Leap Network Competitive Analysis

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#103]
# Bounty
compare against other chains

## Scope
- POA
- Loom
- Matic Network
- TRON
- EOS
- NEM
- Stellar

## Deliverables
- fill out this: https://docs.google.com/spreadsheets/d/1QKeo0t2mNo3QqGJYIhu0_iN412HlNCQgNtTokUS00zM

## Gain for the project
- ability to compare and convince projects

## Roles
bounty gardener: @johannbarbie / 15%
bounty worker: @kohola71  / 60%
bounty reviewer: name / 25%

**Comment by kohola71** [comment]
I'll take it

**Comment by kohola71** [comment]
I'll filled out the competitive analysis doc: https://docs.google.com/spreadsheets/d/1QKeo0t2mNo3QqGJYIhu0_iN412HlNCQgNtTokUS00zM/edit#gid=0 

Can you review @johannbarbie?

**Comment by johannbarbie** [comment]
no progress
