### ISSUE TITLE
create a post about hackathon results

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#105]
# Bounty

write an article and describe submissions. get some of the submissions working and deployed so people can use them.

## Scope
- *Dapp Submissions:*
  - https://github.com/MaxStalker/leap-round-server, https://github.com/MaxStalker/dungeon-riches-react-basic
  - https://github.com/johngrantuk/burnerbot/tree/leap_plasma
- *Watchtower Submissions:*
  - https://github.com/travisdmathis/leap-watcher
- *Exit Market Maker Submissions:*
  - none :shrug:

## Deliverables
- blog post
- links where submissions can be tested

## Gain for the project
- visibility for ecosystem dapps

## Roles
bounty gardener: @johannbarbie / 15%
bounty worker: name / share
bounty reviewer: name / share

**Comment by kohola71** [comment]
Here's the link to the draft: https://docs.google.com/document/d/1EXyHbX4j0eB3AjGuOWEr9uwsvbVlet3zMAPFPjzA6q4/edit

**Comment by kohola71** [comment]
@MaxStalker could you point us to your hackathon submission?
