### ISSUE TITLE
Prepare Thetta release

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#106]
- [x] Reapply leapdao/leap-node#263 🎂 (distributed breeding / staging)
- [x] Merge https://github.com/leapdao/leap-node/pull/268 (tendermint 0.31.5, merging with tendermint-node etc)
- [x] Review, test and merge https://github.com/leapdao/leap-node/pull/231 (tx decoding and co 💥breaking change for the network)
- [x] Test and merge https://github.com/leapdao/leap-core/pull/68 (`getUnspents` to require second argument, 💥breaking change for the frontends)
- [x] Test and merge https://github.com/leapdao/leap-core/pull/101 (handling sendTransaction response without receipts)
- [x] ~Finish, test and merge https://github.com/leapdao/leap-node/pull/252 (bug fix for shadow validator functionality)~
- [x] ~Implement, test and merge https://github.com/leapdao/leap-core/issues/39 (💥readonly inputs)~
- [x] make sure integration tests are working once all the above things are merged
- [x] make sure bridge-ui is working once all the above things are merged
- [x] do a smoke test once all the above things are merged: deposits, transfers, scons execution, exits, node restarts
- [x] make an npm release

**Comment by johannbarbie** [comment]
suggest to add https://github.com/leapdao/leap-node/pull/268 to list

**Comment by troggy** [comment]
theta is running on testnet for a while, integration tests are working (https://github.com/leapdao/integration-tests/pull/30). The only thing not really checked by me is spencon execution, though tested by Max and his game.
