### ISSUE TITLE
Update testnet to the "Migration" release

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#111]
# Bounty

## Prerequisites
- all the development tasks in "[Mainnet Migration](https://github.com/orgs/leapdao/projects/8)" project are delivered and new leap-node release is created

## Scope
- update leap-node version on testnet nodes to run "Mainnet Migration" release ([leap-node@5.2.0](https://github.com/leapdao/leap-node/releases/tag/v5.2.0))
- upgrade bridge contracts to "Mainnet migration" release ([leap-contracts@1.1.0](https://github.com/leapdao/leap-contracts/releases/tag/v1.1.0)):
  - Bridge
  - FastExitHandler
  - SwapRegistry
- make sure all the infrastructure is working: 
  - bridge UI
  - faucet
  - sniper rifle
  - tx store

## Deliverables
- testnet running updated nodes
- announcement in #testnet channel about the network upgrade

## Publicly visible delivery
- tweet about testnet update

## Gain for the project
- prepare the ground for mainnet update

## Roles
bounty gardener: @troggy / 15%
bounty worker: @troggy / 85%
bounty reviewer: no review needed / only check leap-node versions. Actual review is done in #112

**Comment by eshavkun** [comment]
Aren't we already there?

**Comment by troggy** [comment]
Nopes, these still need to be done: https://github.com/leapdao/leap-node/issues/234 and https://github.com/leapdao/leap-node/issues/242

https://github.com/leapdao/leap-node/issues/242 is a breaking change for testnet, so another migration for testnet will be needed 🤦‍♂️

**Comment by troggy** [comment]
done except the tweet. Logs: https://leapdao.slack.com/archives/CFKUNHHC7/p1561480388001300
