### ISSUE TITLE
Verify the final release is conforming to acceptance criteria

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#112]
# Bounty

## Prerequisites
- https://github.com/leapdao/meta/issues/111

## Scope
- verify all the points in the criteria list below. Comment if something could not be reasonably verified

## Deliverables
- message in #ops channel that you verified everything and release is good to go on mainnet

## Gain for the project
- ensure the release is good to go on mainnet

### Publicly visible delivery
🤷‍♂️

## Roles
bounty gardener: @troggy / 15%
bounty worker: @troggy + @johannbarbie / 85%
bounty reviewer: reviewed by reality

# Acceptance Criteria
> Original: https://hackmd.io/5S9i6bhMTfa2b5zA0IBcAQ?both

## integration tests
  - [x] run => pass

## tendermint upgrade 0.3 / lotion transaction encoding
  - [x] smoke test -  deposit / transfer / exit of ERC20 and ERC721
  - [x] ~load test~ _Excluded for now_

## plasma exits 
  - [x] run valid exit of utxo (output pos 0) => tokens received, get stake back
  - [x] run valid exit of utxo (output pos 1) => tokens received, get stake back
  - [x] run valid exit of utxo (output pos 15)  => tokens received, get stake back
  - [x] run invalid exit, challenge exit => exit canceled, get stake back

## ~getUnspents to require second argument~
  @troggy: _It is still [possible](https://github.com/leapdao/leap-core/pull/110/files#diff-27a1c86133de4310373decfdad200a91R160) to call `getUnspents` without second argument, will be working like before_
  - [x] call getUnspents() without second argument
  - check following application to not be affected:
	  - [ ] dungeon riches
	  - [x] bridge-ui
	  - [x] sniper riffle
	  - [x] tx-store
	  - [ ] burner-wallet

## ~shadow validator~
  - [x] ~run 2 validators, stop active one, activate passive one ([instructions](https://leapdao.slack.com/archives/CFKUNHHC7/p1557316379018900?thread_ts=1557316243.018700&cid=CFKUNHHC7)), network should continue.~
Not doing shadow validator anymore (it is dangerous — we had the data corruption + [you can get slashed](https://twitter.com/zmanian/status/1145072296723275776))

## Nonfungible Storage Token
  - [ ] register ERC1948 => token receives color
  - [ ] deposit NST => NST output should appear in getUnspents()
  - [ ] modify data of NST => check that data field in output updated
  - [ ] exit NST => check that data field in token corresponds with set data

## Distributed Breeding
  - [x] register ERC1949 => token receives color
  - [ ] deposit queen => queen output should appear in getUnspents()
  - [x] send queen into breeding condition => transfer success
  - [x] breed => worker created
  - [ ] exit workers => worker minted in rootchain contract
  - [ ] exit queen => breed counter is updated to latest breedcount on sidechain
  - **negative tests:**
	  - [ ] try to exit worker after queen exited => should fail, but not block queue
	  - [ ] deposit worker into breeding condition => breed tx should fail
	  - [ ] try to convert worker to queen (plasma and root chain contract should prevent this)
	  - [ ] try to call breeding condition with queen that doesn't belong to condition => should fail
  - [ ] deposit another queen, try to exit worker from previous queen => worker can exit

**Comment by troggy** [comment]
NFT for testing: 0xED2903d13584Deff039ECd59Bb1beC7508f7513b. Owned by Rinkeby multisig
ABI (ERC721Full): 

```
[{"constant":true,"inputs":[{"name":"interfaceId","type":"bytes4"}],"name":"supportsInterface","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x01ffc9a7"},{"constant":true,"inputs":[],"name":"name","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x06fdde03"},{"constant":true,"inputs":[{"name":"tokenId","type":"uint256"}],"name":"getApproved","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x081812fc"},{"constant":false,"inputs":[{"name":"to","type":"address"},{"name":"tokenId","type":"uint256"}],"name":"approve","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0x095ea7b3"},{"constant":true,"inputs":[],"name":"totalSupply","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x18160ddd"},{"constant":false,"inputs":[{"name":"from","type":"address"},{"name":"to","type":"address"},{"name":"tokenId","type":"uint256"}],"name":"transferFrom","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0x23b872dd"},{"constant":true,"inputs":[{"name":"owner","type":"address"},{"name":"index","type":"uint256"}],"name":"tokenOfOwnerByIndex","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x2f745c59"},{"constant":false,"inputs":[{"name":"from","type":"address"},{"name":"to","type":"address"},{"name":"tokenId","type":"uint256"}],"name":"safeTransferFrom","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0x42842e0e"},{"constant":true,"inputs":[{"name":"index","type":"uint256"}],"name":"tokenByIndex","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x4f6ccce7"},{"constant":true,"inputs":[{"name":"tokenId","type":"uint256"}],"name":"ownerOf","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x6352211e"},{"constant":true,"inputs":[{"name":"owner","type":"address"}],"name":"balanceOf","outputs":[{"name":"","type":"uint256"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x70a08231"},{"constant":true,"inputs":[],"name":"symbol","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function","signature":"0x95d89b41"},{"constant":false,"inputs":[{"name":"account","type":"address"}],"name":"addMinter","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0x983b2d56"},{"constant":false,"inputs":[],"name":"renounceMinter","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0x98650275"},{"constant":false,"inputs":[{"name":"to","type":"address"},{"name":"approved","type":"bool"}],"name":"setApprovalForAll","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0xa22cb465"},{"constant":true,"inputs":[{"name":"account","type":"address"}],"name":"isMinter","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function","signature":"0xaa271e1a"},{"constant":false,"inputs":[{"name":"from","type":"address"},{"name":"to","type":"address"},{"name":"tokenId","type":"uint256"},{"name":"_data","type":"bytes"}],"name":"safeTransferFrom","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0xb88d4fde"},{"constant":true,"inputs":[{"name":"tokenId","type":"uint256"}],"name":"tokenURI","outputs":[{"name":"","type":"string"}],"payable":false,"stateMutability":"view","type":"function","signature":"0xc87b56dd"},{"constant":true,"inputs":[{"name":"owner","type":"address"},{"name":"operator","type":"address"}],"name":"isApprovedForAll","outputs":[{"name":"","type":"bool"}],"payable":false,"stateMutability":"view","type":"function","signature":"0xe985e9c5"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor","signature":"constructor"},{"anonymous":false,"inputs":[{"indexed":true,"name":"account","type":"address"}],"name":"MinterAdded","type":"event","signature":"0x6ae172837ea30b801fbfcdd4108aa1d5bf8ff775444fd70256b44e6bf3dfc3f6"},{"anonymous":false,"inputs":[{"indexed":true,"name":"account","type":"address"}],"name":"MinterRemoved","type":"event","signature":"0xe94479a9f7e1952cc78f2d6baab678adc1b772d936c6583def489e524cb66692"},{"anonymous":false,"inputs":[{"indexed":true,"name":"from","type":"address"},{"indexed":true,"name":"to","type":"address"},{"indexed":true,"name":"tokenId","type":"uint256"}],"name":"Transfer","type":"event","signature":"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"approved","type":"address"},{"indexed":true,"name":"tokenId","type":"uint256"}],"name":"Approval","type":"event","signature":"0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925"},{"anonymous":false,"inputs":[{"indexed":true,"name":"owner","type":"address"},{"indexed":true,"name":"operator","type":"address"},{"indexed":false,"name":"approved","type":"bool"}],"name":"ApprovalForAll","type":"event","signature":"0x17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31"},{"constant":false,"inputs":[{"name":"_to","type":"address"},{"name":"_size","type":"uint32"},{"name":"_isGlowing","type":"bool"},{"name":"_color","type":"uint8"}],"name":"mint","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0x9235bddd"},{"constant":false,"inputs":[{"name":"_tokenId","type":"uint256"}],"name":"burn","outputs":[],"payable":false,"stateMutability":"nonpayable","type":"function","signature":"0x42966c68"}]
```

**Comment by troggy** [comment]
verified `deposit / transfer / exit of ERC20 and ERC721`. 8 NFT-related issues found in Bridge UI, yet on the network side everything is good 😂

**Comment by johannbarbie** [comment]
verified first few point in breeding, here the tx: http://localhost:1234/explorer/tx/0x382580bc937b9858d37ae55e4f9bbbd06d90351e32b06375516abab14b60c857

**Comment by troggy** [comment]
the point of these tests is not clear:

```
  - [ ] run valid exit of utxo (output pos 0) => tokens received, get stake back
  - [ ] run valid exit of utxo (output pos 1) => tokens received, get stake back
  - [ ] run valid exit of utxo (output pos 15)  => tokens received, get stake back
```

**Comment by troggy** [comment]
verified plasma exits

The only issue is that Bridge UI watchtower complains about invalid exit even after it was challenged
https://github.com/leapdao/bridge-ui/issues/234

**Comment by troggy** [comment]
partially done, the rest is unfeasible to check according to @johannbarbie . Closing
