### ISSUE TITLE
withdraw mainnet tax and distribute team share

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#116]
# Bounty

claim all period rewards since [last claim](https://leapdao.slack.com/archives/CFQH2UH3Q/p1558109797006700) to latest period.

## Scope
- run [script](https://github.com/leapdao/leap-guardian/blob/master/scripts/claimRewards.js).
- calculate reputation
- distribute according to reputation

## Deliverables
- LEAP token minted and transfered to multisig
- LEAP distributed to team

## Roles
bounty gardener: name / 15%
bounty worker: name   / 85%

**Comment by troggy** [comment]
done

**Comment by johannbarbie** [comment]
this is a repetative one, why not keep it open?

**Comment by eshavkun** [comment]
Agree, it should be open. We just need to update the date of next distribution

**Comment by johannbarbie** [comment]
reopened for another round

**Comment by troggy** [comment]
https://github.com/leapdao/meta/wiki/Mainnet-Block-Tax-withdrawal-and-distribution
