### ISSUE TITLE
create EventScanner service

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#118]
##  Bounty

The service is part of different challenge services and is able to scan for contract events and push them into Message queues.
![Challenger Services (2)](https://user-images.githubusercontent.com/659301/60591805-82b87b80-9d9f-11e9-9235-029303a047f0.png)

the services maintains a database with following fields:
- key: contractAddr
- lastBlockHeight on network
- rpcEndpoint
- array of SQS ARNs

## Scope
- create a trigger that will invoke the service every x minutes.
- have service scan all events since last invocation.
- have service deliver each event separately to each message queue.
- the service maintains a distance of 10 blocks to the tip of the chain.
- the service stores the new block height after each invocation

## DevOps Requirements
- require less than $5/month of running cost
- provide fail-over
- provide database backup
- provide CD from repo master branch

## Deliverables
- code
- test
- deployment for scheduler, database, massage queue, eventScanner service

## Gain for the project
- ability to challenge invalid exits and dark periods

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: name / 70%
bounty reviewer: name / 20%

**Comment by pinkiebell** [comment]
Do we want to kill this bounty because of standalone app design? Fetching events and having a local TaskQueue is simple enough?

**Comment by johannbarbie** [comment]
i don't trust the "standalone app design", as we have no successful example of it in the project history. But if you want to prove it, here is a chance to deliver it: https://github.com/leapdao/solEVM-enforcer/issues/116

**Comment by troggy** [comment]
why do we need "database backup" in requirements here? I guess it is an overkill, given that the database is not going to store anything non-recoverable.

**Comment by troggy** [comment]
Also I suggest to add "should be designed to run in different environments to prevent vendor lock-in" to DevOps Requirements. We want other people to run these services as well, so we should make them as accessible as possible.

**Comment by johannbarbie** [comment]
i intended to implement it as easy and cheap as possible, using the tech stack we know. you are welcome to propose something new, manage implementation, learn all the lessons in operations, do the implementation again, and then deliver on time 😁

**Comment by pinkiebell** [comment]
You guys know my stance. And @troggy is about right that we always can fetch events from a given range. That means we only have to store the last block height, right? 
Anyway, if we design the other apps as standalone/standard applications, we don't need any of this 🎓

**Comment by johannbarbie** [comment]
talk is cheap. i can't do what you guys are asking, so show me how to do it :)

**Comment by pinkiebell** [comment]
> talk is cheap. i can't do what you guys are asking, so show me how to do it :)

Write it so that it works just fine on your dev machine without a special setup 😛
