### ISSUE TITLE
create ExitChallenger service

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#119]
## Bounty

this service checks for every started exit if the exit is valid. if not it tries to submit a challenge.

![Challenger Services (2)](https://user-images.githubusercontent.com/659301/60591805-82b87b80-9d9f-11e9-9235-029303a047f0.png)

The service uses [prevOut index](https://github.com/leapdao/leap-node/issues/283) to check if the UTXO registered in an exit has been spend by an exit type tx (valid exit), or by another type of transaction (invalid exit). If the UTXO has not been spent at all (should not happen, as [event scanner](https://github.com/leapdao/meta/issues/118) maintains distance to chain tip), the service reports an error through slack. 

## Scope
- receive events from Message Queue (filter out only valid)
- for each event/Exit/UTXO determine valid/invalid
- try to challenge
- if challenge not possible, or UTXO not spent, report on slack
- for each invalid exit, report on slack
- keep an encrypted private key in config used for sending challenges

## DevOps Requirements
- require less than $5/month of running cost
- provide fail-over

## Deliverables
- code
- tests
- deployment

## Gain for the project
- ability to challenge invalid exits

## Roles
bounty gardener: @troggy / 10%
bounty worker: @roleengineer  / 70%
bounty reviewer: name / 20%

**Comment by pinkiebell** [comment]
Ditto:
Let's assume MessageQueue and EventScanner are the same thing on an standalone app - point of view?

**Comment by johannbarbie** [comment]
not a fan. i designed the modularity on purpose, so the challenger services can be stateless, and only the event service needs a DB.

**Comment by johannbarbie** [comment]
bounty timed out

**Comment by troggy** [comment]
Event Scanner is already implemented here: https://github.com/leapdao/challenge-services

**Comment by troggy** [comment]
@TimDaub what was your plan with event scanner? https://github.com/leapdao/challenge-services
Was it designed to be used by many consumers ? E.g. Exit challenger and CAS challenger. Or every consumer is meant to run it is own copy of event scanner?

**Comment by roleengineer** [comment]
Usefull links.
start exit:
https://github.com/leapdao/leap-contracts/blob/master/contracts/ExitHandler.sol#L106
getTxbyPrevOut:
https://github.com/leapdao/leap-node/blob/master/src/api/methods/getTransactionByPrevOut.js
challenge Exit:
https://github.com/leapdao/leap-contracts/blob/master/contracts/ExitHandler.sol#L320
challenge exit example: https://github.com/leapdao/leap-guardian/blob/master/scripts/challengeExit.js (old code) 
Fix for exit double spend. If you roll back or otherwise disable it, you will be able to easily reproduce double spends in Bridge UI https://github.com/leapdao/leap-node/pull/339

**Comment by troggy** [comment]
delivered as https://github.com/leapdao/challenge-services/issues/15 with follow ups of https://github.com/leapdao/challenge-services/issues/17, https://github.com/leapdao/challenge-services/issues/18, https://github.com/leapdao/challenge-services/issues/19
