### ISSUE TITLE
create CAS challenger service

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#120]
## Bounty

This service monitors all period submissions. if it finds any dark periods, it starts a challenge.
![Challenger Services (2)](https://user-images.githubusercontent.com/659301/60591805-82b87b80-9d9f-11e9-9235-029303a047f0.png)

A period is dark, if the CAS bitmap of the period contains a `true` bit for a slot, but the validator of that slot has not sent a periodVote transactions for the given period.

*open question:* to start a challenge, one needs to deposit a stake. could there be a grieving attack where a validator does not submit the vote on chain, but still signs it, then reveals it to get the stake?

## Scope
- for each submitted period, query all periodVotes from leap node
- if any bit in the CAS bitmap is set to `1`, but the validator of the slot has not voted, start a challenge.
- report on slack about challenges.
- keep an encrypted private key in config used for sending challenges and paying challenge stake.

## DevOps Requirements
- require less than $5/month of running cost
- provide fail-over
- provide CD from repo master branch

## Deliverables
- code
- tests
- deployment

## Gain for the project
- ability to challenge dark periods

## Roles
bounty gardener: name / share
bounty worker: name / share
bounty reviewer: name / share

**Comment by pinkiebell** [comment]
> open question: to start a challenge, one needs to deposit a stake. could there be a grieving attack where a validator does not submit the vote on chain, but still signs it, then reveals it to get the stake?

This could be verified with the CAS bitmap right?
But:
What if the submitter of that bitmap flips CAS bits like a pro?

**Comment by pinkiebell** [comment]
Let's assume MessageQueue and EventScanner are the same thing on an standalone app - point of view?

**Comment by johannbarbie** [comment]
> Let's assume MessageQueue and EventScanner are the same thing on an standalone app - point of view?

code duplication for event scanning with https://github.com/leapdao/meta/issues/119

**Comment by troggy** [comment]
> open question: to start a challenge, one needs to deposit a stake. could there be a grieving attack where a validator does not submit the vote on chain, but still signs it, then reveals it to get the stake?

What if we require that period vote tx should be included strictly in the notarized period? It is how it works in a normal case — there can't be any non-dark period without a quorum period vote txs included in the last blocks.

**Comment by johannbarbie** [comment]
i'm not sure this addresses the problem. the period that includes the votes is the period that follows the period in question, not the same one. and in addition it could be that votes didn't make it in on time, then it would block and stop the chain.

**Comment by troggy** [comment]
yes, you are right 🤔

**Comment by troggy** [comment]
expired. Needs to be resubmitted by gardener

**Comment by johannbarbie** [comment]
let's wait some more :)
