### ISSUE TITLE
Use GasToken for multisig wallets to guarantee quick payouts of bounties

### ISSUE THREAD

**Issue by TimDaub** [leapdao/meta#121]
## Scope

- When a payout is requested it is best to pay the shares immediately as this confirms the willingness to pay of the LeapDAO organization
- Frequently however, gas prices on the Ethereum mainnet are really expensive (up to 20 gwei)
- That makes sending a bounty really expensive for the keybearers and as a whole. An example:

<img width="345" alt="Screen Shot 2019-07-16 at 16 05 05" src="https://user-images.githubusercontent.com/2758453/61301093-87d7ea80-a7e3-11e9-990a-a991ee855f3a.png">

- However, there's this cool idea that you can create a future on gas by using some specific EVM op codes: https://gastoken.io/
- LeapDAO could benefit from buying gas at a low cost (e.g. Saturday mornings) and spend it at peak times (e.g. Friday evenings)

## Deliverables

- In a document, outline a way a user can securely use gas tokens from gastoken.io
- Even better: Build a script that tries to retain a fixed-size pool of gas tokens (e.g. 20$) that LeapDAO Circle keybearers can withdraw a certain quantity for free each day

## Gains for the project

- Qualitative research on the usage of gastoken.io that could be useful for other applications at a later point in time
- Cheaper operation cost for multisig wallets and keybearers
- Quicker payouts for bounty workers

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johannbarbie** [comment]
timed out
