### ISSUE TITLE
Set up DAI exit market on mainnet

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#122]
# Bounty

⚠️**Bounty has EXPIRED. If you want to work on this issue, chime in into comments first** ⚠️

ECO Dev Circle needs DAI exit market for peep.cash. 

## Scope
- make sure FEMM stores incoming receipts before any processing (so they are not lost if there is a bug in FEMM and processing fails)
- add DAI market to mainnet exit market maker config
- bootstrap it with minimal liquidity for testing
- make sure it works with burner/peep.cash

## Deliverables
- updated mainnet FEMM configuration
- updated exit maker maker deployed for mainnet

## Gain for the project
- unblock ECO Dev Circle using mainnet for burner

## Roles
bounty gardener: @troggy / 10%
bounty worker: name / share
bounty reviewer: name / share

## Funded by

- EcoDev Circle (#ecosystem-development on LeapDAO Slack)

**Comment by TimDaub** [comment]
This issue is a duplicate to [that](https://github.com/leapdao/plasma-burner-wallet/issues/236) one.

**Comment by TimDaub** [comment]
@troggy wrote in Slack:

> these are not full duplicates.. issue in meta requires mostly work to be done on exit-market-maker side + on the ops side.
I’d like to make the exit-market-maker lambda more resilient, so users don’t loose money in case of hiccups (that’s what I mention by “not safe”). It has two parts:
>- lambda shouldn’t lose received receipts
> - client(burner) shouldn’t lose receipts before it sent them to lambda (edited) 
bounty in meta covers only the first part, I think + general setup

**Comment by troggy** [comment]
obsolete
