### ISSUE TITLE
fix testnet, or set up a new one ASAP

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#123]
# Bounty

fix testnet, or set up a new one ASAP

## Scope
- contracts
- nodes
- bridge-ui
- sniper

## Deliverables
- testnet good enough to run event

## Gain for the project
unblock planetA dev

## Roles
bounty worker: name / 100%

**Comment by troggy** [comment]
https://leapdao.slack.com/archives/CHSN8R0TG/p1563479325000100
