### ISSUE TITLE
Testnet: check in node data into local git repo

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#125]
# Bounty

We want to be able to quickly recover the network, in case of database corruption due to consensus problems (e.g. conflicting validators). @pinkiebell proposes to periodically check in `.lotion` folder in the local git repo.

## Scope
- init a git repo for `.lotion` folder of testnet validator
- create a cron job to commit the latest changes every 5 minutes, add block height in commit message

## Deliverables
- initialized and regularly updated git repo on testnet validator node
- writeup about the setup

## Gain for the project
- easier to recover from errors spoiling the chain

## Roles
bounty gardener: @troggy / 10%
bounty worker: @troggy / 75%
bounty reviewer: @pinkiebell  / 15%

## Funded by

Ops Circle

**Comment by troggy** [comment]
@pinkiebell how often we should commit the data?

**Comment by pinkiebell** [comment]
I think each 5 minutes should be more than enough. 🙂

**Comment by troggy** [comment]
Added a daily `git gc` to the mix. At some point we will need to trim the history

**Comment by troggy** [comment]
Setup is described here: https://github.com/leapdao/meta/pull/126

Applied for val2.testnet.leapdao.org
