### ISSUE TITLE
write a guest post for the ethBerlin blog

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#127]
# Bounty

<img width="606" alt="Screen Shot 2019-07-29 at 5 00 48 PM" src="https://user-images.githubusercontent.com/659301/62058873-713d8480-b222-11e9-8b9a-7be5c09a5f1b.png">

## Scope
- introduce the game
- introduce the teams involved 
- point to the grant

## Deliverables
- written and reviewed draft

## Gain for the project
- publicity

## Roles
bounty hunter `#1` : @TimDaub / 50%
bounty hunter `#2` : @johannbarbie / 50%

**Comment by troggy** [comment]
https://leapdao.slack.com/archives/CHBFMQ526/p1564497747020100

**Comment by troggy** [comment]
https://medium.com/ethberlin/introducing-planet-a-the-tragedy-of-the-co%E2%82%82mmons-90e35c229475
