### ISSUE TITLE
deploy spending condition exits

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#128]
## Bounty

deploy https://github.com/leapdao/leap-contracts/issues/219 to testnet and mainnet.

## Deliverables
- deployment to testnet
- deployment to mainnet

## Gain for the project
- ability to run Planet A without SolEVM

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: name / share
bounty reviewer: name / share

**Comment by troggy** [comment]
why do we need this bounty? It is in included in a network upgrade anyway, no?

**Comment by johannbarbie** [comment]
yeah, we wanted to deploy it ASAP, to prevent invalid exits, i guess.
or was it related to taking planetA on main-net for ethBerlin? 🤔

**Comment by johannbarbie** [comment]
i guess it is not needed, as we never activated spending conditions on main-net.
