### ISSUE TITLE
BBW trip — Kosta

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#132]
# Bounty

From our experience, peeps are more productive when co-located in a same room. Besides, getting to know other peeps in person increases cohesion.

## Scope
- book a flight/train/bus/donkey to Berlin
- find a couch to crash
- get to the airport on time with passport

## Deliverables
- @troggy's body located in Berlin between 18th Aug and 25th Aug

## Gain for the project
- team bonding / meet in person
- valuable insights seeing PlanetA live in action

## Roles
Everything: @troggy / 100%

**Comment by johannbarbie** [comment]
done here: https://etherscan.io/tx/0x0a8fbdcf3fb995c38289498988a5e2bf35f0a648d49b0fc9600896e37b6cb184
