### ISSUE TITLE
Offer: Buy Devcon ticket from TimDaub

### ISSUE THREAD

**Issue by TimDaub** [leapdao/meta#133]
# Bounty

## Scope

- @TimDaub has successfully reserved a ticket for Ethereum Devcon in Osaka, Japan for Oct 8 to Oct 11 2019. All further information here: https://devcon.org/
- Anyone has the chance before August 13 to pay exactly 4787230000000000940 
 WEI to 0x6A1517622feB74A242e68a26F423aE38E020a0b1
- Technically, the ticket should be downloadable by anyone with the correct link: `https://pretix.devcon.org/devcon/5/order/somestuff/someotherstuff/?thanks=yes`
- @TimDaub & @johannbarbie have already access to the ticket link
- It is not yet clear if tickets are supposed to be transferred to another person or if they're bound by name. @TimDaub has written an email to support@ethereum.org to clarify 

## Proposal

- In this issue, @TimDaub is proposing to sell his Devcon ticket to LeapDAO for the exact amount specified above (approx. 999€ or 4787230000000000940 WEI). Tim is selling the ticket for the exact price as it is offered by the Devcon website
- As Tim and Johann have the ticket link, Johann could act as escrow given the potential situation where the ticket is paid by LeapDAO but Tim decides to not send the ticket link
- Tim is proposing that LeapDAO's general circle buys the ticket and that then a member of LeapDAO can make a proposal and go to Devcon
- Tim will wait with paying the ticket in Ether for himself until the very last moment (shorty before August 13). If LeapDAO decides to not buy the ticket from Tim, Tim will buy it himself and go alone lol

<img width="1156" alt="Screen Shot 2019-08-06 at 17 41 08" src="https://user-images.githubusercontent.com/2758453/62554492-809b7e00-b871-11e9-8912-a9c96a8693d1.png">

## Gain for the project

- Have a LeapDAO member go to Devcon and experience three days of great talks, amazing networking and the culture of Japan.

## Roles
No roles. Send the above specified amount to the specified address.

**Comment by johannbarbie** [comment]
@TimDaub what is the size of the request in DAI? the general multisig has no ETH.

**Comment by TimDaub** [comment]
Offer not active anymore.
