### ISSUE TITLE
Build a bounty bot

### ISSUE THREAD

**Issue by TimDaub** [leapdao/meta#135]
## Scope

- Currently bounties can either be filed through GitHub on the respective repository or they're filed through the bounty Google Form
- When filing a bounty through the Google Form, it is automatically posted in the respective Slack channel such that everyone of the circle is made aware but it is not posted to the correct GitHub repository automatically
- Filing a bounty directly on GitHub currently doesn't post into the correct Slack channel
- Additionally, bounties on GitHub are currently not validated on their format, so many bounties are posted with e.g. incorrect formatting or not complying to the bounty template at all

## Deliverables

- Build a bot that 
  - can be configured to listen to any repository on GitHub
  - can be configured with Slack credentials
  - if a new bounty is posted on any of the configured GitHub repositories it:
    - validates the GitHub issue and determines if it's complying with the current LeapDAO bounty template
    - Given that the GitHub issue is a valid bounty, allow the bot to post the issue in the respective Slack channel
      - Ideally there's a mapping between repositories and in which Slack channel their issues should be posted e.g. "Post all valid leapdao/plasma-burner-wallet bounties into #ecosystem-development"

Nice to haves:

- The bot should check if the bounty author has added the label "bounty". If the bounty is valid, it should assign the label. And vice versa
- The bot should make authors aware that their bounty is non-compliant to the LeapDAO bounty policy by e.g. commenting on the issue and prompting the author to make edits

## Gain for the project

- We can get rid of the bounty Google From
- Bounties can be created more efficiently by gardeners
- Gardeners will be incentivized to follow the bounty template more strictly
- More bounties can be challenged within their 2 day challenge period as more members are aware of their existence

## Roles
bounty gardener: @TimDaub / 10%
bounty worker: name / 75%
bounty reviewer: name / 15%

**Comment by johannbarbie** [comment]
question here: https://leapdao.slack.com/archives/C75C00YJD/p1565876421001100?thread_ts=1565780576.019500&cid=C75C00YJD

**Comment by TimDaub** [comment]
> question here: https://leapdao.slack.com/archives/C75C00YJD/p1565876421001100?thread_ts=1565780576.019500&cid=C75C00YJD

Can't access the question...

**Comment by troggy** [comment]
![image](https://user-images.githubusercontent.com/163447/67483752-2095c600-f66f-11e9-853b-646585465f10.png)

**Comment by johannbarbie** [comment]
timed out
