### ISSUE TITLE
offboarding bounty (pinkiebell)

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#136]
## Bounty

when off-boarding is needed?
- partner leaves the team. (announced in message or personal conversation)
- partner becomes inactive. (no contact for 2 weeks)
- partner engages repeatedly in [unacceptable behaviour](https://github.com/leapdao/meta/blob/master/CODE_OF_CONDUCT.md)

## Scope
- remove AWS access
  - IAM user and access tokens
  - SSH keys for servers
- rotate out of keypass file
- rotate keys if in knowledge of any validator keys
- handover of knowledge/domains
- update of all roles in holacracy
- rotation out of any key-bearing
- try to contact partner, get feedback and goodby message

## Deliverables
- communication with necessary partners to complete checklist
- presentation of completed checklist at next tactical

## Gain for the project
- emotional closure
- avoidance of security issues and incidents

## Roles
bounty gardener: @johannbarbie / 20%
bounty worker: @articobandurini / 70%
bounty reviewer: name / share

**Comment by articobandurini** [comment]
@troggy @johannbarbie @sunify - only you have all the rights enough to revoke @pinkiebell's access. i have asked you already on slack - but no reaction. i am asking you again here: PLEASE DO SO.

**Comment by troggy** [comment]
@johannbarbie I've corrected [the checklist](https://trello.com/c/Flbo16ux/51-offboarding-procedure) to use the Roles not actual people. To me looks like the bounty is done, it's gardener's turn now :)

**Comment by johannbarbie** [comment]
i know i'm not a reviewer, but how have these 2 points been handled?
1. SSH keys for servers
2. rotate keys if in knowledge of any validator keys

also i would need a proof that 1. has been done before 2. otherwise the person could just gain knowledge of 2. by using 1.

**Comment by johannbarbie** [comment]
on `ec2-52-19-146-63.eu-west-1.compute.amazonaws.com`:
```
ubuntu@ip-172-31-24-215:~$ cat .ssh/authorized_keys 
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDD8JyP+d57A2h7dRoY/YadLZM2BtsOh4zLMhW3ZdTluXbvx6lD+Z/rJQF67BDuTXO8NxQ9BJLEWVHZohbpxD9HAZBUGWi7WjLm7v05wUvT40zcvJP00a1q/Xvuuz1Ie07/q9INIGTOHV7g4Yb/Au9iTxOcKBQkfnhUKZKZInt71Vv2WtTWPxTXo3Yg0fKEY78huiJKW70rwM2N6JHTOvYAOxKGt4Nf6c2eN4EmUEhS6W2DsLVnyW949FRHtPjBipazQY2uyXLlfCQlSj1XCrgVYoy5LeuM8rwbatmsNlwOqFfgyRnw1JOI6kavJzVc+58YNwX47Cyd6VKNaXQzx4Sl leap_auth
```
i know for sure that @pinkiebell  has this key, as i've shared it with him. this is on the main-net validator.

**Comment by troggy** [comment]
that's true 🤔

Okay, I will figure it out. I was under impression that this bounty is about the offboarding _procedure_ definition, not the actual offboarding of a particular person.

**Comment by troggy** [comment]
@johannbarbie verify pls https://leapdao.slack.com/archives/CHSN8R0TG/p1569934435001800

**Comment by johannbarbie** [comment]
looks good. that solved `1.`, now only validator keys are left

**Comment by troggy** [comment]
> now only validator keys are left

Do you think Tendermint key also needs to be rotated, or Ethereum's one is enough?

**Comment by johannbarbie** [comment]
🤔 
good point. i guess we should update the description. but for this instance signer key rotation enough.

**Comment by troggy** [comment]
I cannot swap the validator key right now, because of [the bug](https://github.com/leapdao/leap-node/issues/310#issuecomment-537623226) in the leap-node. It won't be fixed in a nearest future, can we split this bounty somehow? I see that deliverables are delivered

**Comment by johannbarbie** [comment]
> Gain for the project
> - avoidance of security issues and incidents

it is kind of a binary thing. either the scope of people that can insert a dark period into the chain got reduced, or not. i'm not sure which achievement a first fraction of a bounty would be paid for 🤷‍♂

**Comment by troggy** [comment]
> i'm not sure which achievement a first fraction of a bounty would be paid for

rotated SSH keys? Revoked AWS access? Formalized checklist of off-boarding activities?

**Comment by troggy** [comment]
On a side note, are you still supporting your stance [here](https://github.com/leapdao/meta/issues/53):

> Start reducing scope when 100% of estimate spent.

**Comment by troggy** [comment]
not done yet — validator key is not rotated #164

**Comment by troggy** [comment]
since mainnet is stopped, nothing to rotate
