### ISSUE TITLE
travel for Shareholder agreement

### ISSUE THREAD

**Issue by TheReturnOfJan** [leapdao/meta#138]
# Bounty
Shareholder agreement had to be signed. Flew to Estonia to make it happen, also helped structure the deal.

## Scope
- Book flights to and from Estonia
- Deal with a flight being canceled
- Calculate share distribution and communicate it to a non-technical audience
- Attend meeting at the notary

## Deliverables
- Shareholder agreement is signed

## Gain for the project
- updated share distribution in PlasmaProtocols

## Roles
Everything: @TheReturnOfJan / 100%

**Comment by troggy** [comment]
✅
