### ISSUE TITLE
SMT Ethereum Token Prototype

### ISSUE THREAD

**Issue by roleengineer** [leapdao/meta#140]
# Bounty

 Create a token (like ERC20) that doesn't store balances, but only the merkle root of all data. When token holders want to read balance or send transfers, then they would need to bring proofs. Create a backend (lambda functions) as a small webservice that would track the events in the token contract and provide proofs to who-ever is interested.

## Scope
- contract architecture from best practices (like openzeppelin)
- instead ```mapping (address => uint256) public balances;``` implement Sparse Merkle Tree data structure
- rewrite all basic functions to work with new data structure
- add necessary require statements that appears in regard to new data structure
- write tests for all basic cases
- write lambda function to give users values for parameters that are required by contract function 'balanceOf'
- write lambda function to give users values for parameters that are required by contract functions 'transfer' or 'transferFrom'
- lambda functions, when invokes by users through API Gateway, need to track the contract events and store current state of tree (leaves) to DynamoDB

## Deliverables
- ERC20 contract template based on Sparse Merkle Tree
- AWS webservice that tracks contract events and gives users necessary proofs
## Gain for the project
- ability to create token contracts based on Sparse Merkle Tree
- ability to create webservices for custom contracts
## Roles
bounty gardener: @johannbarbie / %10
bounty worker: @roleengineer / %65
bounty reviewer: @eshavkun / %25

**Comment by eshavkun** [comment]
PR approved:
https://github.com/roleengineer/ERC20_template/pull/2
Deployments:
contract https://ropsten.etherscan.io/address/0x89e5afffc89185af83bc3aa02da227acf30c9acb#code
balanceof https://a81uibpm08.execute-api.eu-west-2.amazonaws.com/default/balanceofl?address=0xcC692921A9D2327B61c3347EB4c07CED0cE7c61c
transfer https://a81uibpm08.execute-api.eu-west-2.amazonaws.com/default/transferl?sender=0xcC692921A9D2327B61c3347EB4c07CED0cE7c61c&recipient=0x812F4FB767d3291F3ad84433D251192cd644e913&amount=1000
