### ISSUE TITLE
Devcon 5 - Trip  - Max

### ISSUE THREAD

**Issue by MaxStalker** [leapdao/meta#147]
# Bounty

Go to Devcon 5 in Osaka. Promote Leap Network and dapps built inside Ecosystem. Look for new contributors and buidlers

## Scope
- Book a flight
- Get to the airport on time with passport
- Attend the conference and related events

## Deliverables
- @MaxStalker located in Osaka during Devcon 5
- @MaxStalker walking around and telling people about how awesome Plasma is

## Gain for the project
- Team bonding with @johannbarbie  and @eshavkun 
- Leatest greatest from the Ethereum meka
- Swag!!! 🐱‍🏍

## Roles
Everything: @MaxStalker  / 100%

**Comment by johannbarbie** [comment]
https://leapdao.slack.com/archives/C75C00YJD/p1568235198002200
