### ISSUE TITLE
Devcon 5 - Accommodation - Max

### ISSUE THREAD

**Issue by MaxStalker** [leapdao/meta#148]
# Bounty
Go to Devcon 5 in Osaka. Promote LeapDAO and dapps built inside Ecosystem. Look for new contributors and buidlers

## Scope
- Book an airbnb
- Save resources by trying to pool with @johannbarbie and @eshavkun 
- Get to the airport on time with passport

## Deliverables
- @MaxStalker located in Osaka during Devcon 5
- @MaxStalker walking around and telling people about how awesome Plasma is
- @MaxStalker singing "Zankoku na Tenshi no Teeze" in the closes karaoke bar

## Gain for the project
- Team bonding with @johannbarbie  and @eshavkun 
- Leatest greatest from the Ethereum meka
- Swag!!! 🐱‍🏍

## Roles
Everything: @MaxStalker  / 100%

**Comment by johannbarbie** [comment]
https://leapdao.slack.com/archives/C75C00YJD/p1568235270002300
