### ISSUE TITLE
send first newsletter with new design/structure to LeapDAO email subscribers

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#149]
# Bounty

let's talk about LeapDAO.

## Scope
- send a newsletter 
- announce some events
- talk about latest developments

## Deliverables
- footer / header / social buttons
- content

## Gain for the project
- keep people up to date

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @zschavi / 75%
bounty reviewer: @MaxKuck  / 15%

**Comment by troggy** [comment]
done?

**Comment by zschavi** [comment]
Basically done, on 02nd October - announcing and asking Newsletter Subscribers for support with gitcoin grants. 

To complete bounty, we need to agree on general newsletter schedule and fitting content for the future. I would like to draft another one before collecting anything.

@MaxKuck is informed, he took care about the feedback to me.

**Comment by johannbarbie** [comment]
now done:
https://mailchi.mp/4cdee319137c/news-flash-from-leapdao-3942551
