### ISSUE TITLE
create pitch to event organizer to run keycard pop-up economy

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#155]
# Bounty

pop-up economies need a tight integration with the organizer (Ethereum meetup / Volt / others). otherwise the on-boarding of users fails, or merchants don't know how to check payments. This bounty is about material for business development and education of event organizers.

## Scope
- what is a pop-up economy?
- what is expected from the organizer?
- what will be delivered by the provider (LeapDAO / Deora)?

## Deliverables
- presentation slides
- template for letter of intent

## Gain for the project
- ability to sell and run pop-up economies using keycard

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @simonweniger  / 70%
bounty reviewer: @johannbarbie  / 10%

**Comment by simonweniger** [comment]
https://docs.google.com/presentation/d/1KdbRYxuYAq8aBzzRHpXcK-PEE_a-1O_vERHehScdgLw
