### ISSUE TITLE
Preparing letter of intent for Status keycard project

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#159]
# Bounty
- writing the keycard project letter of intent

## Scope
- defining project information and key data for the letter
- setting up letter and all legal requirements 
- draft a statement of work from status framing (after input & feedback)

## Deliverables
- letter of intent
- getting a signing from status
- statement of work draft (not part of review)

## Gain for the project
- documentation and higher relevance of Status' commitment 

## Roles
bounty gardener: @MaxKuck 10 %
bounty worker: @johannbarbie @MaxKuck 80 %

**Comment by johannbarbie** [comment]
timed out
