### ISSUE TITLE
submit an application to the Giveth Beta program with LeapDAO

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#160]
# Bounty

Giveth funds public goods. LeapDAO delivers scalability as global public utility. let's try to play together

## Scope
- try to launch a LeapDAO donation Campaign onto Giveth!

## Deliverables
- Test User Account connected on release.giveth.io
- Live User Account connected on beta.giveth.io
- Project Entity name, mission, goals - online elsewhere or in a shared document
- “Last Mile” solution for funds management after disbursement from Giveth
- Submit: [Beta Onboarding Request Form](https://docs.google.com/forms/d/e/1FAIpQLSeXRdJkQP-_wrRPb4jF--cPdviU_9ZVEh7urqaYVWgnCCQl8g/viewform)

## Gain for the project
- attract talent and capital

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @DistributedDoge  / 75%
bounty reviewer: @simonweniger  / 15%

**Comment by DistributedDoge** [comment]
Done, although we may need to wait a little to actually join Giveth:

- [x] Mission, vision goals in a single [document](https://docs.google.com/document/d/1e_dVvOT0dVBj52YZTIH9dSmZq0spuXkESbXP5G7Ru7Y)
- [x] Test and live user accounts (see document) 
- [x] Last mile solution for funds management (folks are quite interested in our process)
- [x] Beta request form 

Giveth members on "Riot" chat told me they are not on-boarding new users at the moment. I asked them to contact me as soon as the situation changes. You can see public chat on Giveth Riot logs to confirm what I wrote: 

> I can't tell you when we'd be able to onboard further new users but I can say, we'll know a LOT more next week, after a few key decisions are made about how we can go forward.

**Comment by simonweniger** [comment]
I reviewed the [documnet](https://docs.google.com/document/d/1e_dVvOT0dVBj52YZTIH9dSmZq0spuXkESbXP5G7Ru7Y/edit) and really like the work. The Mission is well explained and the two best social good use cases of LeapDAO are mentioned. The communication with Giveth happend and we just have to wait that they onboard again. So from my point there is nothing to add and i agree to payout the bounty @johannbarbie @DistributedDoge
