### ISSUE TITLE
Keycard design and production management for first popup economies

### ISSUE THREAD

**Issue by simonweniger** [leapdao/meta#162]
# Bounty
Design the Keycard with the specs from the Keycard team: 

This pdf can be used as a base for the design definition.
https://drive.google.com/file/d/11ufzOvRKrB-FiuJ-da9tm12tI_tZU5xx/view?usp=sharing

A .png or .bmp file with 86x54mm ratio is good. In terms of resolution, 2040x1080 is a minimum recommended.

communication with the production company is done by Guy-Louis Grau (guylouis@status.im)

## Scope
- Kickass Design for the cards
- Review interations with the production company 

## Deliverables
- Production ready design files

## Gain for the project
- Knowledge about how to design the cards
- Re usable card design with a LeapDAO branding 
- Brand awearness at the popUp events.

## Roles
bounty gardener: @MaxKuck  / 10%
bounty worker: @simonweniger  / 70%
bounty reviewer: name / 20%

**Comment by johannbarbie** [comment]
bounty timed out
