### ISSUE TITLE
write welcome message for announcement channel in Slack

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#167]
# Bounty

- currently people join an empty channel

## Scope
- create a welcome message that separates the target groups, and send the to the right channels and link relevant roles. target groups are:
  - validators
  - ecosystem leads
  - contributors
- be catchy
- create invite link that can be monitored by Dev Link

## Deliverables
- text + post
- invite link

## Gain for the project
- better on-boarding funnel

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @simonweniger  / 80%
bounty reviewer: @johannbarbie  / 10%

**Comment by simonweniger** [comment]
Hier mein Einladungslink:
https://join.slack.com/t/leapdao/shared_invite/enQtNzkzMzU2MDE3MzAxLWIyM2E2Y2MxYzRiNDE1MzQzNjhiMzQxZTk4OTgyYmVlN2RmODYwN2NkY2MyNzA3MWZkZDRlOWQyMDY0NzZhNmU

Haben wir schon einen welcome massage bot ? Ansonsten würde ich folgenden vorschlagen: https://slack.com/apps/A2LJCT3GR-greetbot

Folgenden text würde ich Vorschlagen:
<img width="394" alt="Bildschirmfoto 2019-11-01 um 15 52 17" src="https://user-images.githubusercontent.com/43147663/68033274-a3e29780-fcbf-11e9-8a50-09972049cd9a.png">

**Comment by simonweniger** [comment]
:leapy: *Welcome to LeapDAO* :leapy:

Hey there :wave: We’re glad that you joined LeapDAO. To make your start as easy as possible @Simon Weniger will contact you as soon as possible and be your connection for all regards. I am sure you want to get started, so what is next? :rocket:

There are some channels you should join:

#ecosystem-development
#00_leap_dao
#01_escrow_council
#random

You also should visit the https://leapdao.org/resources.html for all informations around the organization. There you can find everything from the white paper to our current bounties.

If you wanna check what bounty are currently open and get right into the contribution check out GitHub: https://github.com/leapdao   :tada:

**Comment by johannbarbie** [comment]
fixed spelling:
`You should also visit the https://leapdao.org/resources.html for all information around the...`

**Comment by johannbarbie** [comment]
can we describe channels like this?
```
general circle: #00_leap_dao
DEV circle: #20_d_for_development
ECO circle: #ecosystem-development
finances: #01_escrow_council
jokes: #random
```
