### ISSUE TITLE
Validator Q&A

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#169]
# Bounty
Write a Q&A document/text to resolve frequent questions from validator side

## Scope
- create a document that collects x most relevant questions and short precise answers.
- create a space where (prospect) validators can ask questions.
- write a role proposal for Q&A maintainer.

## Deliverables
- first Q&A
- slack channel or other means of communications
- role proposals to maintain and update Q&A

## Gain for the project
- infrastructure to keep validators happy.

## Roles
bounty gardener: @MaxKuck  / 10%
bounty worker: @simonweniger  / 70%
bounty reviewer: @johannbarbie  / 20%

**Comment by simonweniger** [comment]
https://docs.google.com/document/d/1CRbWOuttc-70PGZGkSOaDK9oKpwkn1x_Nz9fkQ4STQY/edit

**Comment by simonweniger** [comment]
https://app.glassfrog.com/organizations/14849/orgnav/roles/12171553/overview

**Comment by simonweniger** [comment]
**Validator Q&A added to the LeapDAO docs** https://docs.leapdao.org/validators/
**Second version as a google docs** https://docs.google.com/document/d/1CRbWOuttc-70PGZGkSOaDK9oKpwkn1x_Nz9fkQ4STQY/edit#

**Validator Slack chanel is live** https://leapdao.slack.com/archives/CQ5T4BWR2

**Validator Link role is created** https://app.glassfrog.com/organizations/14849/orgnav/roles/12171553/overview
