### ISSUE TITLE
Governance proposal about block rewards

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#170]
# Bounty
setting up a validator is not trivial and requires continuous care. This effort should be rewarded in speculative means (Leap token), but also provide a continuous income (DAI). Which incentives can be created to enable stable network operations?

## Scope
- propose a tax rate for the first distributed set of operators.
- define bounties that reward the setup of new validators.
- define a way to reward operations and uptime for validators.

## Deliverables
- governance proposal
- bounty for setup
- bounty or automated payout for uptime.

## Gain for the project
- first distributed set of operators

## Roles
bounty gardener: @MaxKuck  / 10%
bounty worker: @simonweniger  / 70%
bounty reviewer: @zschavi / 20%

**Comment by troggy** [comment]
requesting to define `continuous care`

**Comment by troggy** [comment]
I have couple of concerns here:
1. We don't know if "continuous care" is needed. It is just a guess. So it is probably not something which stops people from running testnet validators and thus better be excluded from the scope or rephrased like "people fear that continuous care will be needed".
2. I suspect such bounties create wrong incentives. Today I heard the phrase like "if there won't be any money in the multisig, I will stop working on the project" — it is pity that there no love in the project, just a desire for money

**Comment by troggy** [comment]
On a bright side, I totally support the initiative to figure out why people are not starting new validators

**Comment by johannbarbie** [comment]
> requesting to define continuous care

- making sure the hardware is ok and network is on
- keeping software up to date
- withdrawing block rewards
- monitoring challenge functions and write/improve scripts to cater to them.

**Comment by johannbarbie** [comment]
> it is pity that there no love in the project, just a desire for money

true, and ideally every-one can afford to work on things they like to some extend.

I also see that people are interested to contribute, but are simply held back by the need to have a regular income. the policy is meant to address these needs.

**Comment by simonweniger** [comment]
https://docs.google.com/document/d/1kOUQUbYK8bdRJBsOFR7hM1Wf98EH-CEPtURHb1Iv7GM/edit#heading=h.oz1gxcjjb7kr

**Comment by simonweniger** [comment]
https://github.com/leapdao/meta/issues/178  -- Accepted in the Governance call 18.11.19

**Comment by johannbarbie** [comment]
cool
