### ISSUE TITLE
setup motion-cannes-demo on testnet

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#171]
# Bounty

- we had this demo: https://docs.google.com/presentation/d/1QabUcFLZQLx3VS9e-QRiF-EmTk5tYjbiII-zlROVC4Q

## Scope
- demo was running on staging testnet
- staging testnet has been turned off
- needs to be redeployed on current testnet

## Deliverables
- working streaming site
- working burner wallet
- working plugin

## Gain for the project
- motion can do demos
- bounty payment to be deducted from token-swap deal

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @johannbarbie / 90%
bounty reviewer: name / 0%

**Comment by eshavkun** [comment]
@johannbarbie Which action is required on this bounty? If it needs review I can do it

**Comment by johannbarbie** [comment]
this one is already done and reviewed by Alan. we only wait for the $$$ to come in.
