### ISSUE TITLE
validator introduction [pair programming]

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#173]
# Bounty
validator introduction

## Scope
- describe roadmap
- describe token economics
- describe chain governance

## Deliverables
- text for page/docs
- one-pager (email introduction)
- gPresentation

## Gain for the project
- ability to pitch all validator companies 

## Roles
bounty gardener: @johannbarbie   / 10%
bounty worker: @simonweniger @johannbarbie  / 80%
bounty reviewer: @zschavi   / 10%

**Comment by eshavkun** [comment]
@johannbarbie @simonweniger Do you have any update on this bounty?

**Comment by simonweniger** [comment]
yeah structure and first pieces of content are ready. We're planing to finish it this week.

**Comment by eshavkun** [comment]
@johannbarbie @simonweniger Any update? Should I put this issue back to available so others can pick it up?

**Comment by johannbarbie** [comment]
moving forward, and i've started the review already.

**Comment by eshavkun** [comment]
@johannbarbie You're worker, you can't be reviewer. And why did you remove me from gardening and revieweing (silently)

**Comment by johannbarbie** [comment]
actually only @simonweniger is working on it, updated the description.

**Comment by johannbarbie** [comment]
> And why did you remove me from gardening and revieweing (silently)

because i have written the description of the bounty, and have been single point of contract for the worker.

**Comment by simonweniger** [comment]
Text Document: https://docs.google.com/document/d/1eou1K6bru5n-i5L6M6d6-nJ1kpisKCW-kXA43ATj4is/edit#

Pitch - Präsentation: https://docs.google.com/presentation/d/1hfhYzLYLCCZw9r3iDTWnWKedNMD7aIoDuGQ1-ApFUbs/edit

**Comment by johannbarbie** [comment]
paid out here: https://leapdao.slack.com/archives/C75C00YJD/p1576195810002600
