### ISSUE TITLE
Create an Onboaring document for new members 

### ISSUE THREAD

**Issue by simonweniger** [leapdao/meta#175]
# Bounty
Create a document that the DEV Link can send to new members, which helps them to understand the current state of LeapDAO, Holocracy, the Bounty system as well as where to find everything they need.

## Scope
- collect all important documents
- descripe the roadmap
- explain where to start
- explenation of Holocracy and the Bounty system

## Deliverables
LeapDAO branden PDF 

## Gain for the project
better accesability for new members, helps to onboard them end to become a permanent contributer to the Organisation

## Roles
bounty gardener: @MaxKuck   / 10%
bounty worker: @simonweniger  / 70%
bounty reviewer: @MaxKuck  / 20%

**Comment by johannbarbie** [comment]
NOT an objection: does it need to be a pdf? why not a wiki page on github?

**Comment by simonweniger** [comment]
yees good idea! I am going to do it inside of the **LeapDAO/meta** wiki

**Comment by scenaristeur** [comment]
Hi my name is David, I'm a French Dev interested in Décentralisation & Holacracy.
I've just discovered Colony & LeapDao and want if I can contribute. 
As I'm a newbie in Leap, I could be at first a 'tester' for the onboarding doc and a French translated if you want. ( Just subscribe on slack with 'Smag0' name) 👍

**Comment by simonweniger** [comment]
Done -->  https://github.com/leapdao/meta/wiki/Home---Onboarding

**Comment by MaxKuck** [comment]
reviewed
