### ISSUE TITLE
Validator Invasion - Phase 1 "Sphere of Influence"

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#177]
# Bounty
While exploring the Cosmos, flag officer Simon found a online storage facility which contained massive amounts of data, which can help the Leap-Starfleet and fuel the next mission of the spaceship...

## Scope
- Get a feeling for the validator business & explore the possibilities of the business model
- Check for already supported networks & projects of existing validators
- Create a full contact list of potential Leap validators to approach in Phase 2

## Deliverables
- spreadsheet summarising all Validator: names, websites, networks & contact information

## Gain for the project
- Exploring the global validator community and outline possible partnerships
- One file to have all necessary information put in place

## Roles
bounty gardener: @simonweniger / 10%
bounty worker: @zschavi / 80%
bounty reviewer: @simonweniger  / 10%

**Comment by simonweniger** [comment]
awesome **way more** than i expected !!
