### ISSUE TITLE
Bounty for Validator Setup & UpTime (weekly recurring) 

### ISSUE THREAD

**Issue by cyan-one** [leapdao/meta#178]
# Bounty
Setup of a Validator in the testnet to help the development and testing. Contribute to the Validator offering roadmap with your hands on knowledge.

**This bounty payout is per Validator Operator and not per Validator**

## Scope
- making sure the hardware is ok and network is on
- keeping software up to date
- withdrawing block rewards
- monitoring challenge functions and write/improve scripts to cater to them

## Deliverables
- give a weekly status report to the LeapDAO validator link about bugs, errors, problems or good things. 
- be there as a tester if developers have questions on how the node software is doing
- stay online 24/7 

## Gain for the project
pool of Validator testers to accelerate the validator roadmap

## Roles
bounty gardener: @simonweniger  / 10%
bounty worker: name / 80%
bounty reviewer: @simonweniger / 10%

**Comment by troggy** [comment]
still relevant?

**Comment by troggy** [comment]
not relevant and ignored :)
