### ISSUE TITLE
off-boarding bounty (tim)

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#179]
## Bounty

when off-boarding is needed?
- partner leaves the team. (announced in message or personal conversation)
- partner becomes inactive. (no contact for 2 weeks)
- partner engages repeatedly in [unacceptable behaviour](https://github.com/leapdao/meta/blob/master/CODE_OF_CONDUCT.md)

## Scope
- remove AWS access
  - IAM user and access tokens
  - SSH keys for servers
- rotate out of keypass file
- rotate keys if in knowledge of any validator keys
- handover of knowledge/domains
- update of all roles in holacracy
- rotation out of any key-bearing
- try to contact partner, get feedback and goodby message

## Deliverables
- communication with necessary partners to complete checklist
- presentation of completed checklist at next tactical

## Gain for the project
- emotional closure
- avoidance of security issues and incidents

## Roles
bounty gardener: @MaxKuck  / 40%
bounty worker: @johannbarbie  / 40%
bounty reviewer: name / 20%

**Comment by johannbarbie** [comment]
removed AWS account and terminated EC2 instances started in Frankfurt.

**Comment by troggy** [comment]
done?

**Comment by troggy** [comment]
probably done
