### ISSUE TITLE
Harmony X LeapDAO - research & call

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#183]
# Bounty
- Harmony chain reached out for a call.

## Scope
- research Harmony, estimate their position in the market
- Prepare few ideas for the call
- set up a call and pitch ideas

## Deliverables
- pre-call research
- call
- call notes

## Gain for the project
- depending on call outcome
- best: possible new projects on Harmony

## Roles
bounty gardener: @zschavi / 10%
bounty worker: @zschavi & @johannbarbie / 80%
bounty reviewer: @johannbarbie  / 10%

**Comment by johannbarbie** [comment]
call with great potential, notes here: https://leapdao.slack.com/archives/C5R9Y2292/p1574868964008100
