### ISSUE TITLE
LeapDAO's December Newsletter

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#186]
# Bounty
Many things happened, let's keep the mailchimp audience informed!

## Scope
- inform about LeapDAO's achievements, updates & projects

## Deliverables
- announce upcoming newsletter, post subscription link
- new newsletters to be send until 13.Dec.2019

## Gain for the project
- keep a closer link to the subscribers
- summarize the monthly achievements

## Roles
gardener/worker: @zschavi  / 85%
bounty reviewer: @MaxKuck  / 15%

**Comment by johannbarbie** [comment]
paid out here: https://leapdao.slack.com/archives/C75C00YJD/p1576195741001800
