### ISSUE TITLE
heartbeat challenge service

### ISSUE THREAD

**Issue by cyan-one** [leapdao/meta#188]
## Problem Description

- when a validator goes offline, it puts the network at risk of halting (2/3 of signatures from validator set needed).
- => ideally dead validators are removed ASAP, so that the can not halt the BFT consensus.

## Scope

- create a service that regularly monitors heartbeats of all slots
- if a slot is offline, the service should start a challenge in the contract.
- once a challenge duration finished, the service should finalize the challenge.

## Deliverables

- code
- tests
- deployment

## Gain for the project

- reduced risk of network halting.

## Expert / Affected

expert: @johannbarbie 

## Roles
bounty gardener: @simonweniger  / 10%
bounty worker: name / share
bounty reviewer: name / share

**Comment by troggy** [comment]
@simonweniger can you define "a slot is offline" please? I'd like to to make this a bounty ready to be taken?

**Comment by simonweniger** [comment]
in the PoA operator contract the challenge game for the heartbeats is implemented:
https://github.com/leapdao/leap-contracts/blob/master/contracts/PoaOperator.sol#L354

according to @TheReturnOfJan  the current implementation does not support to check heartbeat inclusion in multiple periods. hence “slot is offline” currently means any period without heartbeat.

@johannbarbie  suggests to still implement it that way that the challenge is only opened once 3 or more consecutive periods don’t show a heartbeat.

**Comment by troggy** [comment]
@johannbarbie @TheReturnOfJan given that current heartbeat implementation is easy to trick [1], does it still make sense to finish this task? What do you think? There is a new contributor interested in taking this bounty.

I think it may still worth finishing this one, since all the other parts are already done, though usefulness of the current design is doubtful

**Comment by troggy** [comment]
@simonweniger you are the gardener here, so it is your call

**Comment by troggy** [comment]
Docs about validator heartbeats: https://github.com/leapdao/docs/pull/61/files#diff-d79a180fb1d7f719483f4a7f71835d85

**Comment by troggy** [comment]
expired. Needs to be resubmitted by gardener
