### ISSUE TITLE
Initial Research and Budget Estimatation for WhiteRabbit

### ISSUE THREAD

**Issue by MaxStalker** [leapdao/meta#189]
# Bounty
WhiteRabbit approached LeapDAO and asked us to estimate how much it would cost to create custom solution for their product

## Scope
- research use of burner v2 as foundation for WR
- define and estimate as much of Stage 1-3 as possible

## Deliverables
Prepare a budget proposal based on research and feature request in the following list:
### Preparation Stage
- Burner Wallet v1 comparison to Burner Wallet v2
- Explore modular system of v2
- Check ecosystem of Burner v2 (amount of project that used or currently using it)

### Stage 1
- functional
  - integrate plasma into Burner Wallet
- For **Streamer** audience
  - integrate it into streaming site (k5.leap.rocks)
  - design interface for integration (https://docs.google.com/drawings/d/1IOnBXGE9fgScMTNJkUconAWYxjoV1dvuIJDk2rjxayw/edit)
  - pay for movies with crypto
  - Burner v1/v2 to be able to pay for movie
  - (Optional) Add account management (hedgehog)
  - (Optional) Add fiat on-boarding (bity)

## Stage 2

- functional
  - proof service that enables split payments
- Interface for **Producers**
  - to mint tokens (route in Burner Wallet)
  - review by Alan/Bruno
  - to add other rightsholders to existing movie
- **Streamer**
  - (if not stage 1) Add account management
  - (if not stage 1) Add fiat on-boarding
  - split payments

## Stage 3
- improvements for features and requests from Stage 1 and 2

## Gain for the project
Great partner that would like to move forward together with Leap Network

## Roles
bounty gardener: @MaxStalker / 10%
bounty worker: @MaxStalker / 80%
bounty reviewer: name / 10%

**Comment by johannbarbie** [comment]
done here: https://leapdao.slack.com/archives/CHBFMQ526/p1576598877001100
