### ISSUE TITLE
Application for MakerDAO Grant // Pair Programming

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#191]
# Bounty
Identifying synergies of MakerDAO and LeapDAO. Applying to the grant with a project that is aligned to our roadmap goals and vision of the Leap Network.

## Scope
- fulfilling the requirements of the grant application
- explain goal to get traction on the DAI and Leap Network
- setting the focus on zero-knowledge proof implementation as a pDAI project for the grant application
- making ~~in-depth~~ research for zk proof on plasma 
- point out the advantages of layer-2 solutions combined with zk proof and DAI

## Deliverables
-  two page detailed description outlining exactly what the project does, how it works, the problem it solves, and a projected budget
- ~~sending it to **grants@makerdao.com**~~ _[The program will re-open on February 1, 2020](https://community-development.makerdao.com/grants)_.

## Gain for the project
- funding to boost Leap Network development into the right direction
- gain traction for Plasma adaptation

## Roles
bounty gardener: @MaxKuck 10%
bounty worker: @MaxKuck  / 45%
@johannbarbie  45%

**Comment by MaxKuck** [comment]
Info: https://community-development.makerdao.com/grants

**Comment by MaxKuck** [comment]
changed to size M, zk proof research not needed for now

**Comment by MaxKuck** [comment]
changed worker to @johannbarbie

**Comment by vrde** [comment]
Related: #204

**Comment by MaxKuck** [comment]
needs submission in the beginning of February

**Comment by MaxKuck** [comment]
submitted on February 3, 2020
