### ISSUE TITLE
Treasury: recover LEAP allocation records

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#194]
# Bounty

We have a Tax policy which allocates chunks of LEAP token supply for different purposes (partners, bounties, merkle mine etc). However, we are not tracking how much of each chunk is already allocated, so it is hard to say how much is left etc

## Scope
- recover records for LEAP allocations already happened and put them on treasury sheet available for everyone to check

## Deliverables
- updated treasury spreadsheet

## Gain for the project
piece of mind for token allocations

## Roles
bounty gardener: @troggy / 30 DAI
bounty worker: name / share
bounty reviewer: name / share

**Comment by saumyabratadutt** [comment]
Can I work on this bounty? Is the allocation record on Github?

**Comment by troggy** [comment]
@saumyabratadutt this bounty is about figuring out how much tokens we've spent already and on what. The tricky part here is not filling a spreadsheet, which is trivial, but figuring out the numbers.

**Comment by saumyabratadutt** [comment]
> @saumyabratadutt this bounty is about figuring out how much tokens we've spent already and on what. The tricky part here is not filling a spreadsheet, which is trivial, but figuring out the numbers.

Most transactions must have been done through SAI, so I'll need to verify those numbers. Right?

**Comment by edsphinx** [comment]
This bounty is available?

**Comment by troggy** [comment]
I don't think it is needed anymore

**Comment by troggy** [comment]
closing as [outdated](https://app.glassfrog.com/organizations/14849/orgnav/policies/11706380)
