### ISSUE TITLE
create a proof-data provider for sparse-merkle-trees

### ISSUE THREAD

**Issue by roleengineer** [leapdao/meta#195]
# Bounty
Create a service with an API that allows devs add their sparse-merkle-trees(manually or copy sparse-merkle-tree from a smart contract) to the provider's database, update them and get proofs in various ways.
Needed for Dapps to run on Plasma, they need storage. Plasma is restricted in storage to 32 bytes per NFDT. Devs will need to generate proofs for different data structures to hold more data.

## Scope
- build a set of services running on Docker Compose to store proof-data for sparse-merkle-trees
- use [sparse merkle tree](https://github.com/deora-earth/voting-contracts/blob/master/test/helpers/SmtLib.js) with any key length and values of 32 bytes
- provide an endpoint to store proofs for key-value pairs
- provide an endpoint to generate proofs for each key/value pair

## Deliverables
- code
- deployed service

## Gain for the project
- simplify development of apps with client-side storage management.

## Roles
bounty gardener: @roleengineer / 10%
bounty worker: @roleengineer / 65%
bounty reviewer: @troggy  / 25%

## Funded by
Dev circle

**Comment by troggy** [comment]
@roleengineer I suggest don't use AWS here. We want this thing to be as accessible as possible, so better stay away from vendor lock-in. Besides we've [commited](https://twitter.com/leapdao/status/1198979915821068289) to be decentralized 😆

**Comment by troggy** [comment]
@roleengineer also suggesting to add some background about why it is needed (like the paragraph you posted on Slack)

**Comment by roleengineer** [comment]
@troggy  Ok, I add this paragraph and discover Tim's experience. Also, look for over approaches.
