### ISSUE TITLE
Create UTXO Challenger for Token Governance

### ISSUE THREAD

**Issue by MaxStalker** [leapdao/meta#196]
# Bounty
One of the requirements of Token Governance is that members could vote with their UTXO, which will hold specific amount of LEAP tokens and would not be spent on the moment, when proposal started.
When new voice is casted, smart contract will emit event, exposing the address of the voting person as well as UTXO hash, which then can be used to check and challenge casted vote.
You can reference smart contract code and interface [here](https://github.com/leapdao/leap-contracts/issues/261)

## Scope
- create script or micro service, that will listen to vote events and check that provided UTXO is valid

## Deliverables
- working script or micro service
- tests

## Gain for the project
This will allow org to ensure that all votes are valid and prevent from "double spending" tokens to cast more votes on harmful or lobbied proposals.

## Roles
bounty gardener: @MaxStalker  / 10%
bounty worker: name / 80%
bounty reviewer: name / 10%

**Comment by johannbarbie** [comment]
this RPC function will be super useful to find transactions that Spend an UTXO:
https://github.com/leapdao/leap-node/blob/master/src/api/methods/getTransactionByPrevOut.js

**Comment by troggy** [comment]
expired. Needs to be resubmitted by the gardener
