### ISSUE TITLE
design and document a validator off-boarding flow

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#197]
# Bounty
validators want to be able to leave a slot without getting slashed. how to go about that?

## Scope
- validator onboarding
- validator offboarding

## Deliverables
- extend validator registration form
- create offboarding form (slack bot)
- draft accountabilities to validator link & propose in gov

## Gain for the project
- ability to unstake

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @simonweniger  / 75%
bounty reviewer: @MaxStalker  / 15%

**Comment by johannbarbie** [comment]
**Validator Flow:**
- updated registration form: https://docs.google.com/forms/d/e/1FAIpQLSdQtc5LoEyWkc5-86SOLW3xK8cRNwuByC7SIrA9MdWeAiuBZw/viewform
- created sign-off form: https://docs.google.com/forms/d/e/1FAIpQLSfYr8h6jLgoqdhr7-y6NRA7qw6RS0PRX4LqxrcYb2W-6t6csQ/viewform

**Validator Link Flow:**
- created instruction for validator link:
https://docs.google.com/document/d/1H0Mx_0aQyJN6toNnR4_EoxjDKN2q-niFnkWAGoGN7Ak
- created checklist in spreadsheet to be followed by validator link:
https://docs.google.com/spreadsheets/d/1uvneoaIrVV1xpRqDX-HFhjUKIjOgz3XNBGWxLksIrhA

**Comment by MaxStalker** [comment]
Concerning `updated registration form`:
thins link - [https://docs.leapdao.org/connect/](https://docs.leapdao.org/connect/) - have information about installing leap-node package from npm. So I belive, 1 step in form is redunant :)

**Comment by johannbarbie** [comment]
paid out as #91
