### ISSUE TITLE
Article for Frontiers in Blockchain

### ISSUE THREAD

**Issue by DistributedDoge** [leapdao/meta#198]
# Bounty

[Frontiers in Blockchain](https://www.frontiersin.org/journals/blockchain) scientific journal collaborates with organizers of Blockchain For Science [conference](https://www.frontiersin.org/research-topics/11721/the-2nd-international-conference-on-blockchain-and-web3-for-science-research-and-knowledge-creation) to create a collection of scholarly articles on topic of "adoption of Blockchain and associated technologies and cryptoeconomic principles to the science and research environment". Submission deadline is **28 March 2020.** Since we were at the conference showcasing **SolEVM enforcer,** we could follow-up with article on the same topic.

(Looking for expert input from SolEVM folks as per new policy!)

## Scope
- Write an article(~8000 words) + abstract
- Make sure it is factually correct
- Format according to [guidelines](https://www.frontiersin.org/about/author-guidelines)
- Respond to peer-review
## Deliverables

Manuscript+abstract to be submitted to the collection. If the article passes peer-review, we would need to pay additional **1,150USD** publishing fee to have it included in the collection (which I hope could be covered by ECO or General circle?).
## Gain for the project

We get publication in (relatively new) open access journal. Most importantly, external peer-review for SolEVM Enforcer concept.  According to the email they boast:

•  High visibility with a freely downloadable e-book
•  Rigorous, transparent and fast peer review
•  Advanced impact metrics 

## Roles
bounty gardener: @DistributedDoge 
bounty worker: @DistributedDoge + open for collaborations!
bounty reviewer: name / share (+external review from Frontiers)
expert: @johannbarbie, JK

**Comment by DistributedDoge** [comment]
Keeping a log to keep myself accountable: What I am doing right now is collecting references (using Zotero) and sketching an outline. Will share it on slack once it is ready.

**Comment by Clearwood** [comment]
Is it possible to still support you on this?

**Comment by DistributedDoge** [comment]
Yes, you are more than welcome! There is still time till submission deadline and I want to catch up with recent developments (Optimistic Virtual Machine, Enforcer => EMO) so I would welcome a second pair of eyes on that one. Let's coordinate on Slack.

**Comment by johannbarbie** [comment]
timeout
