### ISSUE TITLE
LeapDAO Podcast 🎤 - Prologue & Preparations 

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#201]
# Bounty

## Scope
- create "pre-show" notes: suitable questions and outline general podcast theme
- research, setup and prepare all materials like banner, texts & general presentation 
- check for suitable hosting and all necessary distribution channels.

## Deliverables
- define topic of first episode: questions, pre show notes
- graphics & presentation materials, general speaking & branding
- decide on hosting & maintenance option

## Gain for the project
- have fun & extend LeapDAO's visibility & reach.
- educate followers about Dapps, Plasma, Web3 & why LeapDAO's kicks ass.
- secure a pole position as the frontrunners of scaling solutions for Ethereum, by educating all listeners about various topics & matters.

## Roles
bounty gardener: @zschavi / %
bounty worker: @zschavi / %
bounty reviewer: name / %

**Comment by troggy** [comment]
is it still relevant?

**Comment by zschavi** [comment]
dead issue, thx for heads up @troggy
