### ISSUE TITLE
Pitch & Proposal for Lympo.io to use LeapPlasma

### ISSUE THREAD

**Issue by cyan-one** [leapdao/meta#203]
# Bounty
Lympo.io is looking for a scalable blockchain alternative to ethereum. They currently talking with EOS and Harmony. This bonuty is to create a pitcha and propose them to use our chain.

## Scope
- create a pitch
- write introduction mail 
- offer a call / meeting to propose the use of the Leap Network

## Deliverables
- Mail to Lympo with pitch
- Meeting or Call offering to Lympo

## Gain for the project
Organisation with traffic for the Network

## Roles
bounty gardener: @simonweniger  / -
bounty worker: @simonweniger  / 85%
bounty reviewer: name / 15%

**Comment by johannbarbie** [comment]
expired, needs resubmitting
