### ISSUE TITLE
Explore posibilities of utilizing DAI Savings Rate for our multisigs

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#207]
# Bounty

Our DAI are just sitting, while they may yield some profits via DSR (approx 300 DAI per month!).

Some of the possibilities:
1. Lock DAI in DSR, change Bounty Payout contract to withdraw from DSR on payout (costs ~170k gas)
2. Lock DAI in CHAI, do payouts in CHAI. Burden of unwrapping is shifted to payee.
3. Lock DAI in DSR, unlock 3000 back to DAI every week to pay the bills (3K DAI ~ our weekly burnrate). This way it's just a single 170k gas payout a week, but probs more hastle

Reference:
https://blog.makerdao.com/why-the-dai-savings-rate-is-a-game-changer-for-the-defi-ecosystem-and-beyond/
https://oasis.app/save
https://chai.money/

## Scope
- measure gas costs (in ETH) and implementation costs (in DAI, minutes and gray hair) to implement all the options and present for comparison
- present a conclusion. I'd argue that the first option is most convenient (around extra $0.24 per tx at 8 gwei gas price, we can live with that)

## Deliverables
- comparison table/writeup
- conclusion writeup

## Gain for the project
extra money for projects

## Roles
bounty gardener: @troggy / 20 DAI
bounty worker: @saumyabratadutt / share
bounty reviewer: @troggy / share

## Funded by

General Circle

**Comment by saumyabratadutt** [comment]
🤚🤚🤚
I want to work on this project.

**Comment by troggy** [comment]
writeup by @saumyabratadutt 

**Conclusion**
Security: DSR is the most safe, Compound is a runner up (less decentralized).
Gas costs for withdrawal: very close, almost about the same. 200k for DSR on average. 240l for Compound on average.

Suggested follow up for this bounty:
1. Put all the treasury in DSR
2. Change BountyPayout contract to withdraw from DSR on payout (+200k gas)
3. Create PayoutFromDSR contract for normal DAI withdrawals (reimbursements etc). It should: withdraw from DSR, do the transfer.
4. Deploy all new BountyPayout for all the multisigs. Deploy PayoutFromDSR for all the multisigs
