### ISSUE TITLE
write a post about negative interest money

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#208]
# Bounty

take this:
https://docs.google.com/drawings/d/10wkd3Km9p-fx4U0gPf3Ylj9Grifb8h4Y4UhJEMfk_aY
![DDAI - negative interest money](https://user-images.githubusercontent.com/659301/73338011-e80d1600-4275-11ea-85d2-82a97eeaab88.png)

## Scope
- write an article explaining the idea
- mention moloch, colony, bounties

## Deliverables
- post

## Gain for the project
- position LeapDAO as thought leader in "help[ing] collectives of people to collaborate on things they care about".

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @zschavi | @johannbarbie  / 80%
bounty reviewer: @MaxKuck  / 10%

**Comment by johannbarbie** [comment]
the following topics have been forked out due too excessive complexity:
- talk about money theory
- mention anicca (impermanence)
- negative interest money

**Comment by MaxKuck** [comment]
Updated Reviewer Role to me:

Review: 
nicely written and really interesting concept for simpler & transparent collaborations. A concept worth a try in the real world

actions:
- corrected spelling mistakes
- edited wording and sentences for simpler understanding
- changed name to TribalDAO - explains the organisation type better
