### ISSUE TITLE
Improved social media reporting

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#210]
# Bounty

## Scope
* find a way to display social media metrics using data analysis tools

## Deliverables
* share the tools & code used to display the new reporting workflow

## Gain for the project
* social media performance & reports are not solely composed of images & screenshots, but can be documented, analysed & archived in an improved structure.

## Roles
bounty gardener: @zschavi / 10%
bounty worker: @DistributedDoge  / 80%
bounty reviewer: name / 10%

**Comment by zschavi** [comment]
@DistributedDoge - any update to share the code ?
we could use the script for next analysis :)

**Comment by johannbarbie** [comment]
expired, needs resubmitting
