### ISSUE TITLE
Setup two testnet sentinels

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#215]
After [upgrade](https://github.com/leapdao/meta/pull/213) testnet is running validators only. Sync up 2+ sentinels and remove validator from the RPC load balancer.

## Scope

- cleanup and install security updates on old sentinels (2 nodes)
- sync 2 sentinels with testnet
- Load Balancer: exclude validators, include sentinels

## Deliverables

- testnet RPC load balancer using only sentinels

## Funding Circle

General Circle

## Bounty Owner/Gardener

@troggy as *Testnet Commander*

## Gain for the Role

robust testnet operations during EthTurin

## Roles
bounty gardener: @troggy/ 20 DAI 
bounty worker: @troggy / 85%
bounty reviewer: name / share

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by troggy** [comment]
setup `sen1` and `sen4` nodes. Both included in Load Balancer

**Comment by johannbarbie** [comment]
- [x] verified load balancer
- [x] dialed in to instances, checked logs, config and version (both v6.0.1)
