### ISSUE TITLE
Blogpost: Showcase cost per tx on layer 2 depending on block load

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#218]
# Bounty

take this: https://docs.google.com/spreadsheets/d/1ywhXffNw3sNzngvblu4hxE6d2ZbSQ_GjN2JFfl3vYFc/edit#gid=1760753624

## Scope
* explain the measurements & interpretations
* compare plasma, roll-ups & roll-ups with contract tx

## Deliverables
*  post 

## Gain for the project
* proof of activity to followers and contributors
* position LeapDAO as thought leader for layer2 solutions

## Roles
bounty gardener: @zschavi / 15%
bounty worker: @clearwood  / 70%
bounty reviewer: @zschavi  / 15%

**Comment by Clearwood** [comment]
https://github.com/leapdao/leapdao-website/pull/151

**Comment by johannbarbie** [comment]
delivered here: https://leapdao.org/blog/scalability-rollups-not-cure-all/
