### ISSUE TITLE
Blogpost: how we integrated colony reputation with holacracy

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#219]
# Bounty
take this:
https://build.colony.io/t/how-we-integrated-colony-reputation-with-holacracy/286/4?u=johba

## Scope
- expand on johbas forum post, explain how we organize, mention glassfrog & holacracy
- how we use colony
- how we use forked gnosis msg

## Deliverables
- post

## Gain for the project
- position LeapDAO as pioneers in holacracy practics & layer 2 technologies

## Roles
bounty gardener: @zschavi / 15%
bounty worker: @clearwood  / 70%
bounty reviewer: @zschavi / 15%

**Comment by Clearwood** [comment]
[WIP] first draft
https://github.com/leapdao/leapdao-website/pull/146

**Comment by troggy** [comment]
delivered
