### ISSUE TITLE
One week of daily tweets - Challenge

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#220]
# Bounty

## Scope
- research & review possible twitter content in #07_social_content
- report on twitter performance, once the 7/7 posts are done
- increase impressions & clicks by daily tweets

## Deliverables
- daily twitter post

## Gain for the project
- preserve the quality of twitter channel through valuable content & insights to LeapDAO
- increase visibility for LeapDAO

## Roles
bounty gardener/worker: @zschavi / 85%
bounty reviewer: @johannbarbie  / 15%

**Comment by zschavi** [comment]
Tweets:
1/7 - https://twitter.com/leapdao/status/1231953728007294978
2/7 - https://twitter.com/leapdao/status/1232321677868052480
3/7 - https://twitter.com/leapdao/status/1232723277077995525
4/7 - https://twitter.com/leapdao/status/1233024313655283712
5/7 - https://twitter.com/leapdao/status/1233326317069795331
6/7 - https://twitter.com/ParallelePolis/status/1233325946951946240
- https://twitter.com/gluk64/status/1233460837932818432
7/7 - https://twitter.com/leapdao/status/1234170986905440256

**Comment by zschavi** [comment]
Analytics, compared to previous (week)

Metrics Summary:
* Followers: 830 (+8)
* Tweets published: 7 (+175%)
* Impressions: ≈19700 (≈2800 per day)
* Engagement rate: 1.1%
* Link clicks: 112 (+102)
* Likes: 41 (+31)
* Replies: 6 (+5)
* Retweets: 8 (+5)

* Top Tweet: (7500 impressions)
https://twitter.com/leapdao/status/1232723277077995525

**Comment by johannbarbie** [comment]
reviewer summary:
- checked all tweets
- reviewed statistics

👍
