### ISSUE TITLE
Mainnet shutdown

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#222]
aka **Mainnet Execution**

![image](https://user-images.githubusercontent.com/163447/76191574-3ec12480-6212-11ea-864c-de5744f5a704.png)

# Bounty

Mainnet is due to be stopped on 7th of March. Announcement was [posted](https://leapdao.org/blog/mainnet-shutdown) weeks ago. Contracts are [ripe](https://github.com/leapdao/leap-contracts/issues/282) for funds recovery. TIme to execute 🧯

## Scope
- recover funds from Mainnet Plasma and distribute to the owners on mainnet. Keep snapshot of accounts for a while
- recover ETH from mainnet validator back to Ops Circle Multisig
- stop mainnet infrustructure: nodes, tx-storage, faucet etc
- keep mainnet.leapdao.org running but showing a stub with link to "Mainnet shutdown" blog post

## Deliverables
- report to #ops and #mainnet

## Gain for the project
- closure of Mainnet shutdown, releasing mental and physical resources for improving the software

## Roles
bounty gardener: @troggy / 20 DAI
bounty worker: @troggy / 90%
bounty reviewer: name / 10%

## Funded by

Ops Circle

**Comment by troggy** [comment]
- [ ] Stop peeper service
- [ ] Stop public JSON RPC
- [ ] Make accounts snapshot
- [ ] Withdraw LEAP from Plasma Vault
- [ ] Withdraw SAI from Plasma Vault
- [ ] Initialize distribution on LEAP on Mainnet Ethereum
- [ ] Initialize distribution on SAI on Mainnet Ethereum
- [ ] Make a data copy from sentinel
- [ ] Make a snapshot of Mainnet validator
- [ ] Terminate EC2 instances for sentinels and validator
- [ ] Delete LoadBalancer
- [ ] Delete Exit Market Maker
- [ ] Delete Faucet Lambda
- [ ] Delete Bridge UI deployment from S3. Replace with a stub leading to "Mainnet shutdown" post
- [ ] Delete tx-storage lambda
- [ ] Delete leap-peeper lambda

**Comment by troggy** [comment]
Account balances snapshots (LEAP and SAI):
[mainnet-accounts-090320.zip](https://github.com/leapdao/meta/files/4305431/mainnet-accounts-090320.zip)

**Comment by troggy** [comment]
Stubbed https://mainnet.leapdao.org/ with placeholder with explainer

**Comment by troggy** [comment]
Pulling remaining LEAP and SAI from Plasma bridge contract into Leapdao multisig. Initiated [withdrawSupply](https://github.com/leapdao/leap-contracts/issues/282) txs for LEAP and SAI tokens via [General Multisig](https://wallet.leapdao.org/#/wallet/0xC5cDcD5470AEf35fC33BDDff3f8eCeC027F95B1d). Transactions 879 and 880

**Comment by troggy** [comment]
Withdrawn https://etherscan.io/tx/0x9861c3912e331b22ce8aaccba60f348b4aac61e0fc8aa7c41ab1f5dede5d1320
https://etherscan.io/tx/0x9727bf059f4ec40103b7a08935fb57e62920d03e3f5aa23a205dd4bc13219b1c

**Comment by troggy** [comment]
Initialized LEAP and DAI distribution on the Ethereum Mainnet. Tokens will be distributed from Leap General Escrow according to snapshots above 👆[Link](https://leapdao.slack.com/archives/CFQH2UH3Q/p1583816419000400?thread_ts=1583741916.000900&cid=CFQH2UH3Q)

**Comment by troggy** [comment]
Sentinels stopped. Data backed up for a while in s3://leap-data-backup/

**Comment by troggy** [comment]
Sweeped mainnet validator balance to Dev Circle Multisig: https://etherscan.io/tx/0xf2164564b6ed2aec1c0d810cdfc643dc2c49b1f2c51f1ea2aff9fcf6b352b92f

**Comment by troggy** [comment]
Token have been distributed.

LEAP: https://etherscan.io/tx/0xe93cc38606e53da51a912012c0a73d51dfa9e5413e0f4ec23e2824815dd04663

DAI: https://etherscan.io/tx/0xe277b3df957e92ef82fc5f1f49c2f386c81490bae9944296cb174b84b1719314

**Comment by johannbarbie** [comment]
- [x] reviewed and confirmed asset distribution transactions
  - [x] reviewed accounts snapshot
- [x] reviewed aws shutdown:
  - found running cloudwatch rule: [mainnet-tx-storage-sync](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#rules:)
  - found running EC2 instance: [evgeni-node](https://eu-west-1.console.aws.amazon.com/ec2/v2/home?region=eu-west-1#Instances:sort=tag:Name)
  - found lambda remaining lambda functions: [peeper-mainnet-alarm](https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions) and [leap-stats-mainnet-get](https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions)
  - ? what about burner.leapdao.org ?

**Comment by troggy** [comment]
> found running EC2 instance: evgeni-node

this is testnet node, mustn't touch.

Everything else is 👍to remove

**Comment by troggy** [comment]
I guess, peep.cash is also a subject

**Comment by troggy** [comment]
> what about burner.leapdao.org ?
> peep.cash

@johannbarbie How about I upload same index.html there as on https://mainnet.leapdao.org/ ?

**Comment by johannbarbie** [comment]
> > what about burner.leapdao.org ?
> > peep.cash
> 
> @johannbarbie How about I upload same index.html there as on https://mainnet.leapdao.org/ ?

good idea.

**Comment by troggy** [comment]
✅ peep.cash. Uploaded stub
✅burner.leapdao.org CF distribution doesn't exit. Deleted DNS record on Route53
