### ISSUE TITLE
ETH_CC Twitter Coverage

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#223]
# Bounty
LeapDAO attends ETHCC2020, make some noise & show we are actively following the event & community. By providing highlights & insights, we increase the visibility & following.

## Scope
- post the highlight talks of each event day
- provide a mini-teaser/picture of what was discussed
- increase impressions & clicks by posting suitable tweets

## Deliverables
- daily post during the event, summarising the days highlights.
- summarise the ETH_CC week twitter analytics in #05_communications & comment in github issue

## Gain for the project
- show how active LeapDAO is attending community events
- increase LeapDAO's following & visibility

## Roles
bounty gardener: @zschavi  / 10%
bounty worker: @zschavi / 70%
bounty reviewer: @saumyabratadutt  / 20%

**Comment by zschavi** [comment]
**Tweets:**
01.March 20: https://twitter.com/leapdao/status/1234170986905440256

02.March 20: https://twitter.com/leapdao/status/1234614113030098945

03.March 20: https://twitter.com/leapdao/status/1234869143150698498

04.March 20: https://twitter.com/leapdao/status/1235233799706988545

05.March 20: https://twitter.com/leapdao/status/1235647641578586115

**Comment by zschavi** [comment]
**Metrics Summary:**
* Followers: 844 (+14)
* Tweets published: 5 (-2)
* Impressions, total: ≈14700 during last 7 days
Impressions, per day: ≈1700 per day
* Engagement rate: 1.6% (+0.5%)
* Link clicks: 4 (-108)
* Likes: 60 (+19)
* Replies: 2 (-4)
* Retweets: 14 (+6)
* Top Tweet: (4500 impressions)
https://twitter.com/leapdao/status/1235233799706988545

The tweets had some good impact and triggered engagement as well as followers to grow.
Mission accomplished!

**Comment by saumyabratadutt** [comment]
@zschavi already provided most of the valuable metrics. Here's some information that can help in growing the reach.
**Top Influencers engagement from 2020-03-01 until:2020-03-06** 
[https://bit.ly/2IwQm4C](url)

**Twitter Audience related to Eth and Plasma** (sorted by followers)
[https://bit.ly/3aH9p8h](url)

**Comment by zschavi** [comment]
@saumyabratadutt - links are not working :o 
Can you check again ? :)

**Comment by saumyabratadutt** [comment]
> @saumyabratadutt - links are not working :o
> Can you check again ? :)

Updated. Sorry!

**Comment by saumyabratadutt** [comment]
The bounty is complete. Here's the work anyone can view to check the progress.

Twitter Metrics from 01.03.2020 to 05.03.2020 (ETHCC 2020)

✅ Tweets - https://github.com/leapdao/meta/issues/223#issuecomment-596624323
✅ Metrics - https://github.com/leapdao/meta/issues/223#issuecomment-596625815
✅ Top Influencers - https://docs.google.com/spreadsheets/d/16ta2R6gr35Lqx6t7ZhLUKOka4yf6aNoFAGn7iSrNB8w/edit?usp=sharing
