### ISSUE TITLE
Gitcoin Round 5 - Week One

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#228]
# Bounty
Another round of Gitcoin CLR Matching, we use the socials to make some noise, help other projects & gain attention for new purpose & strategies.

## Scope
- Update the Gitcoin Page to express new purpose & strategies
- send a daily tweet shilling other projects, show appreciation & connection

## Deliverables
- daily tweets 23-29 March
- updated grant description on gitcoin grants page

## Gain for the project
- receive attention & DAI's to continue the amazing journey of LeapDAO.

## Roles
bounty gardener/worker: @zschavi / 80%
bounty reviewer: @saumyabratadutt / 20%

**Comment by zschavi** [comment]
Gitcoin Updated Description:

https://hackmd.io/Bv9oG6HnR1-i85THVUqcrQ?view

**Comment by johannbarbie** [comment]
> Gitcoin Updated Description:
> 
> https://hackmd.io/Bv9oG6HnR1-i85THVUqcrQ?view

i've reviewed and condensed it a bit

**Comment by zschavi** [comment]
Final updated gitcoin description:
https://gitcoin.co/grants/66/leapdao-building-a-home-for-dapps-on-layer-2?tab=description

(nearly) daily tweets:
2303: https://twitter.com/leapdao/status/1242056374101651457
2403: https://twitter.com/leapdao/status/1242466547962011650
2503: https://twitter.com/leapdao/status/1242846968637984768
2603: https://twitter.com/leapdao/status/1243200814669332480
2703: https://twitter.com/leapdao/status/1243563340590448640
2803: --- missed out --- // up to reviewer how to handle...
2903: https://twitter.com/leapdao/status/1244216620152651777

**Comment by saumyabratadutt** [comment]
Review:
✔️ **Tweets** : https://github.com/leapdao/meta/issues/228#issuecomment-606092256
✔️ **Metrics** : https://drive.google.com/file/d/1aZ5BklGE0zEVgfdOgx7JeIGiWZVWwlbU/view?usp=sharing (likes, retweets and engagement rate per tweet based on followers).
✔️ **Recommendation** : Usage of hashtags - #Gitcoin or #gitcoin and #GitcoinGrants might increase the reach during the Gitcoin Grants period.
❌ Missed 03.28.2020 but six days worth of work has been submitted hence approve of the work.
🤔

**Comment by zschavi** [comment]
thank you for review and good recommendations
