### ISSUE TITLE
Gitcoin Round 5 - Week Two

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#229]
# Bounty
Another round of Gitcoin CLR Matching, we use the socials to make some noise, help other projects & gain attention for new purpose & strategies.

*Performance based bounty - if we manage to receive more funding tx's & higher matching than last round, bounty size M is accepted. If less or same amount, bounty size S applies.*

## Scope
- research & prepare active approach to other teams, asking for cross funding.
- daily tweets to keep the attention & provide insights.

## Deliverables
- daily tweets 30 March - 06 April
- contact list of requests + reactions

## Gain for the project
- receive attention & DAI's to continue the amazing journey of LeapDAO.

## Roles
bounty gardener/worker: @zschavi / 80%
bounty reviewer: open / 20%

**Comment by johannbarbie** [comment]
out of date?
