### ISSUE TITLE
Nervos: Draft Proposal

### ISSUE THREAD

**Issue by mwaa** [leapdao/meta#230]
# Bounty
Descriptive proposal for [Nervos](https://www.nervos.org/)  partnership exploration

## Scope

- Research on Nervos blockchain
- Review Nervos grants program
- Draft proposal documents with enough content to formulate a proposal

## Deliverables

- Shareable Document with a page for proposal

## Funding Circle

General Circle

## Bounty Owner/Gardener

@mwaa  as **Future Developer Link**

## Gain for the Role

Engage developers with new ideologies to explore, through feedback and comments.

## Roles
bounty worker/gardener: @mwaa / 150
bounty reviewer: @johannbarbie / 50

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [x] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
great work here: https://docs.google.com/document/d/13LkGUXFnIGU68_IpjJA-BvoN3ez51eJSkW9m6_HmtDk

- [x] read through proposals and sources
- [x] improved on spelling
- [x] asked questions where found uncertainty

**Comment by johannbarbie** [comment]
delivered
