### ISSUE TITLE
help team to work out Purpose v4.0

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#234]
# Bounty

[different suggestions](https://hackmd.io/@troggy/leapdao-purpose-4) have been made on the last governance call. until next governance call we want to converge and have 1 or 2 versions to pick from

## Scope

- unachievable purpose (the why)
- strategies (help to make difficult decisions, [article](https://blog.holacracy.org/holacracy-basics-understanding-strategies-f1e244a01df7))
- what to work on now, how to filter the biz-dev pipeline in the future?
- what to write grants for in the future?

## Deliverables

- set of values that can be voted on 
- set of strategies that can be voted on
- questionnaire for new project to determine a coefficient for grants/sales pipeline

## Bounty Owner/Gardener

@johannbarbie as Secretary

## Gain for the Role
a step to be a better team

## Roles
bounty gardener: @johannbarbie / 1/7
bounty worker: @johannbarbie  / 5/7
bounty reviewer: name / 1/7

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform

**Comment by johannbarbie** [comment]
## Step 1
- [x] designed a survey on https://qv.geek.sg/
- [x] executed the survey and analyzed results
  - [egalitarian hopes](https://docs.google.com/drawings/d/1WMm9q3qm5-GRJIi_lIsliV5eacxOdcBhzL8IiG_hzgg)
  - [narcissistic hopes](https://docs.google.com/drawings/d/1LV8__APWtktp5ODeaK1pSJDxdlw8eczuIAt4zDCynBY)

**Comment by johannbarbie** [comment]
## Step 2
- [x] organized [values workshop](https://leapdao.slack.com/archives/C2KNAV6E5/p1590494214015600)
- [x] held workshop on [june 5th](https://leapdao.slack.com/archives/C2KNAV6E5/p1591189861052600?thread_ts=1590494214.015600&cid=C2KNAV6E5)
- [x] applied methods of authentic relating and breakout rooms
- [x] took [notes](https://hackmd.io/rtYjBa4VSD2WARkOx9hI3Q)

**Comment by johannbarbie** [comment]
## Step 3
- [ ] hold next workshop (exceeds bounty scope)
- [x] outsourced to [meta crew](https://app.glassfrog.com/organizations/14849/orgnav/roles/12809527/policies)

**Comment by mwaa** [comment]
- [x] Review of materials delivered
- [x] Proposed an action for the facilitator in meta crew to schedule a call after second RFC on community fund

**Comment by johannbarbie** [comment]
processed
