### ISSUE TITLE
Fill and submit PlasmaProtocols tax report

### ISSUE THREAD

**Issue by eshavkun** [leapdao/meta#239]
# Bounty

## Scope
- Fill in all incoming and outgoing payments for PlasmaProtocls entity
- Generate and submit tax report to Estonian tax authorities
-

## Deliverables
- Submitted tax report

## Funding Circle
General

## Bounty Owner/Gardener
@eshavkun  as PlasmaProtocls board member

## Gain for the Role
Yearly tax report is mandatory therefore must be filled

## Roles
bounty gardener: @eshavkun 
bounty worker: @eshavkun 
bounty reviewer: @johannbarbie 

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by eshavkun** [comment]
[Aruanne_14675345_1591361097.pdf](https://github.com/leapdao/meta/files/4851942/Aruanne_14675345_1591361097.pdf)
Generated report

**Comment by johannbarbie** [comment]
- [x] reviewed submission in https://ettevotjaportaal.rik.ee/?1=1&chlang=eng
- [x] reviewed attached report

=> approved
