### ISSUE TITLE
Hire Scalability Experts for StatusPay Workshop

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#240]
# Bounty
Reach out to experts in the field of layer-2 and other scalability solutions. 

## Scope

- contact experts and reach out to personal network 
- make DAI proposals for experts to join the workshop **No 2** and / or (if possible) have a pre-meeting with questions and better alignment 
- hold meetings with experts upfront and describe the scope of the StatusPay project
- define scope of the contacts field of expertise that is needed during the workshop (define workshop slots)

## Deliverables

- calls with experts (invites for LeapDAO)
- written or verbal agreement of partnership for the workshop
- workshop show-up rate of 100% from respective expert
- brief abstract explaining StatusPay and objectives behind

## Funding Circle

General // Escrow

## Bounty Owner/Gardener

@MaxKuck  as **Biz Dev**

## Gain for the Role

Gain traction for LeapDAO - ensure quality of performance with clients

## Roles
bounty gardener: @MaxKuck  / 70 DAI 
bounty worker: @johannbarbie  / 410 DAI
bounty reviewer: @MaxKuck / 70 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by MaxKuck** [comment]
Review: 
I attended every kickoff meeting with the respective expert from Matterlabs (Alex) and Abridged (James & James) - both on June 8th. Onboarding text have been made for easier explanation. 
![image](https://user-images.githubusercontent.com/45236782/85337289-79f51400-b4e0-11ea-853c-1e32838940d6.png)

Experts kept in the loop via mail / telegram group chats and Status discord channel. Nice expert relation work done here :) 

All experts have been invited to the Workshop No 2 #250 
<img width="411" alt="Screen Shot 2020-06-22 at 10 19 17 PM" src="https://user-images.githubusercontent.com/45236782/85337083-179c1380-b4e0-11ea-86f5-4dd9b1fd9c56.png">

Review complete 👍

**Comment by johannbarbie** [comment]
delivered:
<img width="411" alt="Screen Shot 2020-06-22 at 10 19 17 PM" src="https://user-images.githubusercontent.com/659301/85372184-c4eb4780-b531-11ea-9b55-79254a36a089.png">
and paid out:
https://etherscan.io/tx/0xc1a1d1a372397ab02504dd47349bef5f01d91e4e7afefdfb31efb900250cb2c7
