### ISSUE TITLE
StatusPay - Workshop #1 Preparation // PP

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#241]
# Bounty
Setting up a presentation and workshop agenda/format for the first workshop with StatusPay
(Analysis and Documentation are **separate** bounties)

## Scope

- set up agenda (timing, topics, breaks etc.) and format ideas
- define content of each agenda item
- research and thoughts about content 
- define additional [open questions](https://hackmd.io/@macerer/H1UKOe398/edit) and set priorities for LeapDAO and Status
- finish briefing and preparation material for status 3 days in advance of the workshop (according to [SoW](https://docs.google.com/document/d/1XZwyv1qXqSL57J185iyko2Zr2WL_-GhMLnrPcdvAfdI/edit?usp=sharing))
- identify relevant key stakeholders
- find a time that suits all

## Deliverables

- preparation material
- workshop presentation 
- invite for workshop

## Funding Circle

general // escrow

## Bounty Owner/Gardener

@MaxKuck  as **Biz Dev**

## Gain for the Role

StatusPay as a partner that brings scalability to the masses

## Roles
bounty gardener: @MaxKuck  / 12.5%
bounty worker: @MaxKuck + @johannbarbie  / 50% 30%
bounty reviewer: @pinkiebell  / 7.5%

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by pinkiebell** [comment]
Good work 🎉 Everyone was satisfied. Lot's of information to digest. Post-briefing later on?

**Comment by johannbarbie** [comment]
> Post-briefing later on?

max is on another call now. @pinkiebell  but in 40 min or later may work. pick a time if you like.

**Comment by pinkiebell** [comment]
> > Post-briefing later on?
> 
> max is on another call now. @pinkiebell but in 40 min or later may work. pick a time if you like: https://calendly.com/johannbarbie

The next free slot seems to be on monday 😬

**Comment by johannbarbie** [comment]
ah damn, let's meet now: https://us04web.zoom.us/j/6082518256?pwd=eXJySnlLRHdpWnEvNW9PYVFsejJ0dz09
 @pinkiebell

**Comment by pinkiebell** [comment]
Please wait, says zoom

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MaxKuck** [comment]
Work done here: https://app.mural.co/t/leapdaoxstatuspay1049/m/leapdaoxstatuspay1049/1591623860617/db74218dcfd23150c0a4fd1b651a0aa9932a3307

**Comment by johannbarbie** [comment]
and paid out here: https://etherscan.io/tx/0xc87c1906ffd1665b38c3acdac3cda50959a25bb9d44b14037fe184da86405de6
