### ISSUE TITLE
setup social metrics documentation

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#242]
# Bounty
Until now, social metrics from twitter have been captured simply in slack communications channel. The Social Maintainer can save time & energy if a fixed sheet is in place.

The desired document works as base for tracking social metrics. Next to twitter, website data can be added  later.

## Scope

- browse slack for past metrics, collect data
- find a new format and insert metrics
- add graphics to make the data "snackable"

## Deliverables

- shared spreadsheet
- including all accessible data

## Funding Circle

General Circle
## Bounty Owner/Gardener
@zschavi as **Social Maintainer**

## Gain for the Role

* easier documentation, saves time
* better visualisation of data for presentation & comparison

## Roles
bounty gardener/worker: @zschavi / 150 DAI
bounty reviewer: @saumyabratadutt  / 50 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by saumyabratadutt** [comment]
Here's the review for the bounty. 

✅ [Link to the Twitter Metrics](https://docs.google.com/spreadsheets/d/1OWvmVsu6SHeWBdWjD6ns_UZsykyHRx2gVQw9kclL1xI/edit#gid=0)
✅ Followers are increasing 
✅ Graph looks amazing, one-stop for clean Twitter Data
✅ Maybe we can use tools like [cctip](https://cctip.io/), I personally used it to increase growth. Works pretty well for Twitter Marketing. **(optional)**
