### ISSUE TITLE
write a design doc to integrate CKB childchains with Nervos-DAO

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#243]
# Bounty

The nervos-DAO locks CKB-bytes and gives a inflation issuance to the owner. Let's take that issuance and reward validators and relayers with it.

## Scope

- Research and draft incentive model for grant

## Deliverables

- a document that can be sent over to nervos team
- edit grant proposal to include the incentive model

## Funding Circle

General

## Bounty Owner/Gardener

@johannbarbie  as BizDev

## Gain for the Organization
Approved to proceed with Contract Signing

## Roles
bounty worker: @johannbarbie @mwaa 50% 50%
bounty reviewer: Nervos Technical 

## Gardener checklist

- [ ] I have attached one of the `size-` labels to this bounty
- [ ] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by mwaa** [comment]
Product: https://hackmd.io/mx52xPZuQyejWFItbmQmTg?view
