### ISSUE TITLE
Documentation and Analysis of StatusPay Workshop #1

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#245]
## Bounty
Summing up all the to-dos and insights from the first workshop (issue #241). Sharing it with Status for better decision making and internal rotation. 

## Scope

- set a structure of the workshop results ([Mural Results](https://app.mural.co/t/leapdaoxstatuspay1049/m/leapdaoxstatuspay1049/1591623860617/db74218dcfd23150c0a4fd1b651a0aa9932a3307))
- defining content for documentation from the workshop based on new insights and comments in the mural sheet.
- sense open to-dos and fields unclear that needs attention from Status side
- send out the documentation to the key stakeholders in the StatusPay project
- if needed, reach out with questions to other experts (Alex G / pinkiebell / James Duncan) 
- identify first design decisions and recommendation important for workshop No. 2

## Deliverables

- document in any form desired (preferably Hackmd or google docs)
- email to stakeholders

## Bounty Owner/Gardener

@MaxKuck as **BizDev**

## Gain for the Role

Spread the word and become a thought leader in scaling solutions

## Roles
bounty gardener: @MaxKuck  / 40 DAI 
bounty worker: @johannbarbie  / 470 DAI
bounty reviewer: @MaxKuck  / 40 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by johannbarbie** [comment]
needs review: https://docs.google.com/document/d/1itiNeS95W_-PFU40kA7BWGBQUncymyh-wCLPsSxZ2sI/

**Comment by johannbarbie** [comment]
paid out: https://etherscan.io/tx/0x1702f618b2fe91eb1cedf8cef5f8ee2d67d8b3d01ef704d1a3304fdcf663b76d
