### ISSUE TITLE
StatusPay - Workshop #2 Preparation // PP

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#250]
# Bounty
Prepare workshop formats, content and agenda for the second workshop with StatusPay.

## Scope

- set up agenda (timing, topics, breaks etc.) and format ideas
- identify points unclear from workshop No1 - See: #241 
- take focus on the overall workshop topic: "Scalability" and define the respective content
- create new format for the workshop ("mural")
-  search and thoughts about content - finetune with scaling experts #240 
- scan [LeapDAO documentation](https://docs.google.com/document/d/1itiNeS95W_-PFU40kA7BWGBQUncymyh-wCLPsSxZ2sI) and [StatusPay documentation](https://notes.status.im/1606debrief?view) of the first Workshop 
- finish briefing and preparation material for status 3 days in advance of the workshop (according to [SoW](https://docs.google.com/document/d/1XZwyv1qXqSL57J185iyko2Zr2WL_-GhMLnrPcdvAfdI/edit?usp=sharing))
- find a time that suits all

## Deliverables

- preparation material
- workshop mural 
- invite for workshop

## Funding Circle

StatusPay multisig

## Bounty Owner/Gardener

@MaxKuck  as **Biz Dev**

## Gain for the Role

StatusPay as a partner that brings scalability to the masses

## Roles
bounty gardener: @MaxKuck  / 10%
bounty worker: @MaxKuck + @johannbarbie  / 35% + 55%
bounty reviewer: @pinkiebell  / 10% 

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by MaxKuck** [comment]
result of the workshop: https://app.mural.co/t/leapdaoxstatuspay1049/m/leapdaoxstatuspay1049/1592862033189/b5aca5f9a60b49575e8afcb84f72c1352c760cb9
+ private notes and takeaways

**Comment by pinkiebell** [comment]
🎉 Signed-off-by pinkie

@johannbarbie
Can you add the missing links to the ORU presentation to mural?

**Comment by johannbarbie** [comment]
done :)

**Comment by johannbarbie** [comment]
paid out
