### ISSUE TITLE
StatusPay - Contract Deployment Workshop

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#254]
# Bounty

in a first meeting the [StatusPay Playground](https://nutberry.github.io/playground/) has been presented with the functions of deposit, transfer, exit and the block explorer has been explained. In a further steps contracts need to be deployed by the StatusPay team, to be able to migrate the payment network to Layer-2.

## Scope

- write an explainer document.
- explain functionality and constrains.
- give code examples.

## Deliverables

- published explainer doc
- call with demo

## Bounty Owner/Gardener

@johannbarbie as BizDev

## Roles
bounty gardener: @johannbarbie  / 0 DAI
bounty worker: @pinkiebell  / 1250 DAI
bounty reviewer: @johannbarbie  / 150 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform

**Comment by MaxKuck** [comment]
this has been done: https://nutberry.github.io/basics/
