### ISSUE TITLE
kickstart community fund - MVP specs and project

### ISSUE THREAD

**Issue by MaxKuck** [leapdao/meta#261]
# Bounty
Define and set up the concept of a community owned fund with voting rights. 

## Scope

- set up first concept and design drawings
- present and initiate in governance call
- define clear specifications and calculations
- schedule call for better alignment 

## Deliverables

- hackmd: https://hackmd.io/53ZqiIJnRvqQ3_O3fY_6og?both
- miro design board: https://miro.com/app/board/o9J_kqql47A=/

## Bounty Owner/Gardener

@MaxKuck  as **Process Engineer**

## Gain for the Role

Better processes and stronger connection of the LeapDAO community.

## Roles
bounty gardener: @MaxKuck
bounty worker: @MaxKuck 200 DAI / share
bounty reviewer: @LeapDAO

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by MaxKuck** [comment]
deliverable see hackmd https://hackmd.io/53ZqiIJnRvqQ3_O3fY_6og?both + final MVP call with @pinkiebell

**Comment by MaxKaay** [comment]
delivered and paid out.
