### ISSUE TITLE
kickstart new leap-documentation/wiki

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#262]
# Bounty
as discussed in meta-crew gov/tactical, an improved documentation is desirable:
https://leapdao.slack.com/archives/C010YP2MFBQ/p1594046960004100

## Scope

- gather all existing materials (playbook, bounties, onboarding, policies, reputation)
- define a first draft/outline structure
- identify missing pieces
- where to place/host all visual materials?

## Deliverables

- list of materials to be included
- draft for table of contents
- list of missing pieces
- list of hosting options

## Funding Circle
General Circle

## Bounty Owner/Gardener

@zschavi as **Meta-Crew Rep Link**

## Gain for the Role

better structure for the organisation. all guidelines, policies & onboarding in one place.

## Roles
bounty gardener/worker: @zschavi / (85%) 170 DAI
bounty reviewer: **open** / (15%) 30 DAI

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by zschavi** [comment]
results:
https://hackmd.io/N4NB274qR16pDQHOE5XYUw

**Comment by mwaa** [comment]
@zschavi Good work on collection of materials in one place. Left a few comments which can be part of the implementation
