### ISSUE TITLE
Proposal: "Funding Request Policy"

### ISSUE THREAD

**Issue by zschavi** [leapdao/meta#263]
# Bounty

There is [urgent funding demand by 3 projects](https://leapdao.slack.com/archives/C010YP2MFBQ/p1594752671010700) (WR, Nervos, govBrick).
Bounty aims to create a first "Funding Request Policy" to distribute funds to projects ready to start working.

## Scope

- draft a first policy outline to be discussed in meta-crew call
- define **funding process spec** (why,what,how)
- include community fund, gov-brick, voting
- keep keybearers "clear of suspicion"

## Deliverables

- present to meta-crew upon next gov-tactical

## Funding Circle
**General Circle**

## Bounty Owner/Gardener
@zschavi as **Meta-Crew Rep Link**

## Gain for the Role
- new/existing projects get a specific method to request for funding through community fund

## Roles
bounty gardener/worker: @zschavi / 
bounty reviewer: name / share

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform
- [ ] I have added this bounty to bounty board here https://github.com/orgs/leapdao/projects/6

**Comment by zschavi** [comment]
[Bounty Product - Policy Draft & Ideas](https://hackmd.io/O4XhhwXZTFaBv9ONKZVI6Q?both)
[Funding Request Proposal Template](https://hackmd.io/nPdKMLr5TYi7GcPXQSuDkg?both)

**Comment by mwaa** [comment]
@zschavi Please submit PR request with template inside playbook folder as point of reference.
