### ISSUE TITLE
Berlin Sailing Trip

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#267]
# Bounty

do some team building, go on a sailing trip 💪

## Scope

- rent a boat (200 EUR), buy supplies (60 EUR)
- clean up the boat
- invite people, have fun

## Deliverables

- boat/sailing trip
- every-one comes back happy and safe

## Funding Circle

- 50% deora
- 50% leapdao

## Bounty Owner/Gardener

@johannbarbie  as RepLink

## Roles
bounty gardener: @johannbarbie / 50 DAI
bounty worker: none, only expenses
bounty reviewer: @MaxKuck  / 0

## Gardener checklist

- [x] I have attached one of the `size-` labels to this bounty
- [x] I have submitted this bounty via http://bounty.leapdao.org/viewform

**Comment by johannbarbie** [comment]
![IMG_20200730_142736](https://user-images.githubusercontent.com/659301/88922852-0b3e6f80-d271-11ea-9873-130e32efe829.jpg)

**Comment by johannbarbie** [comment]
trip delivered:
![IMG-20200725-WA0005](https://user-images.githubusercontent.com/659301/88922996-4771d000-d271-11ea-89d0-511674ae6967.jpg) 

![IMG-20200725-WA0007](https://user-images.githubusercontent.com/659301/88922987-450f7600-d271-11ea-809d-e67b75feb0c2.jpg)

**Comment by Clearwood** [comment]
![image](https://user-images.githubusercontent.com/11144110/89649260-be861480-d8c0-11ea-990b-0e3fac946c82.png)
