### ISSUE TITLE
Perfomance tests

### ISSUE THREAD

**Issue by eshavkun** [leapdao/meta#49]
# Bounty :
We need to develop a performance test suit to simulate real Leap network with many users and transactions and see how Leap node works under load
## Flaws:
 - [ ] Deposit
 - [x] Transfer
 - ~~Exit~~ - no need as Exits are done through mainnet
## Deliverables
 * Performance test suit that:
   * Allows to test flows with any number of users and duration
   * Generates results with metrics (transactions per second, throughput etc.) and statistics or the run
## Gain for the project
 * Being able to estimate the actual speed and load limits of the network under load
gardener: @eshavkun | 10%
worker: @eshavkun  | 80%
reviewer: | 10%

**Comment by troggy** [comment]
expired

**Comment by troggy** [comment]
closing as [outdated](https://app.glassfrog.com/organizations/14849/orgnav/policies/11706380)
