### ISSUE TITLE
LeapDAO Playbook 

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#53]
for outsiders it might be hard to understand how we work. write a summary of most important workflows for new-comers.

- How we [manage bounties](https://app.glassfrog.com/policies/10912780). Describe roles:
  - gardener accountabilities: 
    - Sizing of bounties from XS to XL, planning poker, estimated time only one component of size.
    - [bounty board](https://github.com/orgs/leapdao/projects/6)
    - gitcoin
    - ~[waffle](https://waffle.io/leapdao/leap-node)~
  - worker accountabilities: code-style, stay in scope, ask for help
    - Submit PR when 50% of estimate spent.
    - Ask for help (pair programming) when 75% of estimate spent.
    - Start reducing scope when 100% of estimate spent.
    - find a reviewer
  - reviewer: how to do a good code review? 🤷‍♂️ 
- Other ways of contributions
  - [billable](https://app.glassfrog.com/policies/10912781)
  - [salaried roles](https://app.glassfrog.com/policies/10846633)
- How we run sprints
  - 1.5x [reputation](https://app.glassfrog.com/policies/10953641) reward.
  - reducing scope instead of moving deadline

inspiration: https://sophilabs.co/playbook/

## Deliveries
- short and precise markdown file included in this repo.
- link from all contribution guidelines in other repos.
- link from community page.

## Purpose Alignment
- make new contributions easier.
- be more aligned on process and ~hopefully~ deliver future sprints on time.

## Bounty

gardener: @johannbarbie | 15%
worker: ?? | 60%
reviewer: ?? | 25%

**Comment by johannbarbie** [comment]
more inspiration: https://docs.colony.io/colonynetwork/docs-tasks/#roles

**Comment by TimDaub** [comment]
Here's some research I did in my previous company on creating a culture around a decentralized organization. You may find some of the links in the PR interesting: https://github.com/diminator/nautilus/pull/5

Additionally, [here's](https://github.com/TimDaub/nautilus) the repo that was created during the research. Unfortunately it never lead to anything as I didn't find practicable solutions for others to contribute. Hence, a playbook might be a good first step towards a more formal culture 👍

**Comment by NathanSnyder** [comment]
Hey guys, could I meet with one of you about taking this project on?

**Comment by johannbarbie** [comment]
@NathanSnyder sure. how do you want to meet? in Berlin? remote zoom call?

**Comment by troggy** [comment]
expired

**Comment by johannbarbie** [comment]
should we close it?

**Comment by simonweniger** [comment]
yes

**Comment by NathanSnyder** [comment]
> @NathanSnyder sure. how do you want to meet? in Berlin? remote zoom call?

@johannbarbie didn't see your response until you closed this, sorry about that. How about a zoom call next week?
