### ISSUE TITLE
Find memory leak that halts validator

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#60]
1. wait until a validator crashes
2. analyze memory heap and try to identify issue.

related: https://github.com/leapdao/leap-node/issues/175

## Purpose
- stable operations

## Bounty
gardener:
worker:
reviewer:

**Comment by troggy** [comment]
`scp -i ~/.ssh/leap-testnet ubuntu@63.32.254.64:~/node.dump.8493 .`

**Comment by troggy** [comment]
dump seems corrupted :(

postponing till another outage

**Comment by troggy** [comment]
obsolete?
