### ISSUE TITLE
create a proof-data provider for sparse-merkle-trees

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#63]
## Scope
- create a lambda function + simpleDb backend to store proof-data for sparse-merkle-trees
- use [sparse merkle tree](https://github.com/deora-earth/voting-contracts/blob/master/test/helpers/SmtLib.js) with any key length and values of 32 bytes
- provide an endpoint to store proofs for key-value pairs
- provide an endpoint to generate proofs for each key/value pair
- research integration into [web3 plugins](https://medium.com/metamask/introducing-the-next-evolution-of-the-web3-wallet-4abdf801a4ee)

## Deliverables
- code
- deployed service
- specification of contract interface that consumes proofs
- estimate of effort to implement web3 plugin

## Gain for the project
- simplify development of apps with client-side storage management.

## Roles: 
bounty gardener: @johannbarbie / 15%
bounty worker: name / share 
bounty reviewer: name / share

**Comment by eezcjkr** [comment]
Shotgun

**Comment by troggy** [comment]
@johannbarbie should it say ERC1948 now, not ERC721+ERC1537 ?

**Comment by troggy** [comment]
> publish spec of ERC721 in ethMagicians

@johannbarbie I guess is done already here: https://ethereum-magicians.org/t/erc-1948-non-fungible-data-token/3139/3 ?

**Comment by troggy** [comment]
> implement function read and update on ERC721 so that any modification is authenticated

@johannbarbie [done already](https://github.com/leapdao/leap-contracts/blob/master/contracts/ERC1948.sol#L57)?

**Comment by johannbarbie** [comment]
nope, this is not done yet :)

**Comment by johannbarbie** [comment]
bounty timed out

**Comment by troggy** [comment]
Revived as https://github.com/leapdao/meta/issues/195
