### ISSUE TITLE
short announcement about DAI registered

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#70]
<img width="824" alt="screen shot 2019-03-07 at 8 55 44 am" src="https://user-images.githubusercontent.com/659301/53940790-dc8d8b00-40b6-11e9-8142-9118ac8e2d3d.png">

## Scope
- note that governance proposal to register dai finalizes
- talk about xDai vs pDai (plasma DAI)
- list opportunities for wallet providers (fast exit market maker)
- objective: get people to build stuff with it

## Deliverables
- blog post
- twitter post

## Gain for the project
- transaction volume

## Roles: 
bounty gardener: @johannbarbie / 10%
bounty worker: @kohola71  / 60% 
bounty reviewer: @sunify  / 30%

**Comment by kohola71** [comment]
https://docs.google.com/document/d/1S4mWJsc525P3avXi9qtVqqKsoyHwR0rOz6QesW_GJPE/edit
