### ISSUE TITLE
run Ethereum nodes with failover

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#75]
![network setup (1)](https://user-images.githubusercontent.com/659301/54865407-9fd3bc00-4d65-11e9-8a1e-943b50540467.jpg)

## Scope
- set up at least 2 instances (docker with geth/parity)
- put them behind loadbalancer
- create an alarm for unhealthy instances
- post alarms to slack
- run [healthcheck](https://github.com/leapdao/eth-node-healthcheck) that compares block height of our node to etherscan.

## Deliverables
- endpoint for goerli
- endpoint for rinkeby
- endpoint mainnet
- alarms posted into slack #testnet and #mainnet
- instructions how to add new instance to target gorup

## Gain for the project
- have reliable high performing root chain endpoints

## Roles: 
bounty gardener: @johannbarbie / 10% 
bounty worker: @pinkiebell @johannbarbie / 70% 
bounty reviewer: name / 20%

**Comment by johannbarbie** [comment]
https://hackmd.io/hYa53P0oR3Gr9nip7MhXNw

**Comment by pinkiebell** [comment]
One thing:
Extend `-eth-node-healthcheck` to:
- check infura healthyness and local light client healthyness
- decide to which provider to proxy the request
Goal: If infura has a bad day, we still can serve the request (if our node works 😄 )
