### ISSUE TITLE
add bounties on gitcoin (how meta is that!) 🤓

### ISSUE THREAD

**Issue by kohola71** [leapdao/meta#78]
**Scope**
* Review bounties on LeapDAO Github and pick the self-contained bounties from the current or next sprint. Add them on Gitcoin. 

**Deliverables**
* curate 5 issues & size them
* get feedback form the team
* put them on Gitcoin 
* fund them

**Gain for the project:** 
* brings more contributors to the project 

Roles: 
bounty gardener: @kohola71 / 15% 
bounty worker: @johannbarbie  / 60%
bounty reviewer: @kohola71  / 25%

**Comment by johannbarbie** [comment]
https://gitcoin.co/issue/leapdao/leapdao-website/33/2716
https://gitcoin.co/issue/leapdao/bridge-ui/72/2721
https://gitcoin.co/issue/leapdao/meta/61/2717
https://gitcoin.co/issue/leapdao/leapdao-docs/18/2718
https://gitcoin.co/issue/leapdao/leap-core/69/2720
https://gitcoin.co/issue/leapdao/leap-node/116/2719

done
