### ISSUE TITLE
Tendermint migration: set up new network (deploying contracts, starting services) 

### ISSUE THREAD

**Issue by eshavkun** [leapdao/meta#83]
*Size L*
As part of migration to latest Tendermint version new mainnet will be built. This bounty is about setup of the actual new network once other related bounties are completed:
https://github.com/leapdao/bridge-ui/issues/194
https://github.com/leapdao/meta/issues/81
https://github.com/leapdao/leap-contracts/issues/163
https://github.com/leapdao/leap-contracts/issues/164
https://github.com/leapdao/meta/issues/82

## Deliveries
 - [x] Following contracts are deployed for the new mainnet:
    - [x] Bridge
    - [x] Exit Handler
    - [x] Operator
    - [x] SwapRegistry
 - [x] New plasma mainnet is setup:
    - [x] at least one sentinel + AWS loadbalancer
    - [x] validator node
    - [x] call `PoaOperator.setValidator` for the validator node and send some ETH to validator address
    - [x] set up a sniper rifle: deposit 1 LEAP cent to a sniper address, set up a new CloudWatch cron, set up a new domain in SimpleDb
    - [x] set up tx-store
    - [x] set up token faucet (if there was one)
 - [x] Current token is registered on a new Bridge
 - [x] Register other tokens from the existing mainnet
 - [x] Deposits and exits are freezed on the current mainnet
 - [x] Minting rights are transfered to a new Swap Registry
 - [x] "Dispenser" address is fund on the new network
 - [x] UTXOs migration script is run and UTXO set on the new mainnet is equal to the one on current
 - [x] Bridge UI is switched to a new network

## Purpose Alignment
- To finish migration to latest Tendermint version

## Bounty

gardener: | 15%
worker: @troggy | 75%
reviewer: | 10%

**Comment by troggy** [comment]
Contracts deployed on 28.06.2019
Contract version: [v1.1.0](https://github.com/leapdao/leap-contracts/releases/tag/v1.1.0)
Parameters:

```
DEPLOYED_TOKEN=0x78230E69d6e6449dB1E11904e0bD81C018454d7A
POA_REWARD=778000000000000000000 
EPOCH_LENGTH=4 
TAX_RATE=1000 
EXIT_DURATION=151200 
EXIT_STAKE=100000000000000000 
PARENT_BLOCK_INTERVAL=7 
PROPOSAL_TIME=604800 
GOV_ADDR=0x2A224e87b56Eec82B744F2af3BbE753231cE3D87
```
Deployment logs: [deploy-mainnet.log](https://github.com/leapdao/meta/files/3340024/deploy-mainnet.log)

**Comment by troggy** [comment]
> Register other tokens from the existing mainnet

Submitted proposal to add DAI.
sunDAI is not needed, suggesting not to register it with the new network.

**Comment by troggy** [comment]
> Minting rights are transfered to a new Swap Registry

@johannbarbie am I right that the following steps need to be done?
1. Submit proposal to upgrade old SwapRegistry to the version from here https://github.com/leapdao/leap-contracts/pull/189/files
2. Wait 7 days to finalize proposal
3. Call `transferMinter`

**Comment by troggy** [comment]
Draft: https://github.com/leapdao/leap-contracts/releases/tag/v1.1.0-mainnet-v2

**Comment by troggy** [comment]
Requesting to downsize this one to size-M — looks like more accurate in terms of the time spent

**Comment by troggy** [comment]
Delivered:
- https://github.com/leapdao/leap-contracts/releases/tag/v1.1.0-mainnet-v2
- https://leapdao.slack.com/archives/CFQH2UH3Q/p1561724029001100
