### ISSUE TITLE
setup a staging environment for mainnet

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#85]
**Rationale:**
On DAOcon, burner wallet will be running on the mainnet. While we preparing the software for DAOcon, we want to test it against the similar network.

**Requirements:**
- should have exactly the same infrastructure as a mainnet: 
   - load balancer for sentinels
   - same number of nodes with the same security group configuration
   - same leap-node version
   - sniper rifle
   - (optional) token faucet
- additional infstructure:
   - fast exit market maker
- should be using testnet as a root network (rinkeby/goerli)

**Comment by pinkiebell** [comment]
@troggy Still relevant? ;)
