### ISSUE TITLE
Setup leapchain monorepo

### ISSUE THREAD

**Issue by troggy** [leapdao/meta#86]
## Scope:
- include repos:
  - leap-node
  - integration-tests
  - leap-contracts
- consider using some monorepo manager, like [lerna](https://github.com/lerna/lerna) (if needed)
- monorepo should have README explaining how to work with the repo
- add deprecation note to old repos linking to the monorepo. Temporary keep old repos
- preserve commit history of the migrated repos
- look through README for all the repos and docs.leapdao.org and use new repo urls instead of the old urls
- proper versioning of the monorepo
- everything which depended on the previous repos should be changed to work with monorepo
- nothing should be broken with this change

## Deliverables
- new github repo with multiple packages and instructions how to work with it

## Publicly visible delivery
- add "Development setup" page to `docs.leapdao.org` with explainer (similar to README).

## Gain for the project
⚠️no direct impact on the roadmap, so second priority
However:
- it should become easier for ecosystem developers to set up local environment
- easier for developers to make cross-repo changes

**Comment by troggy** [comment]
@sunify @pinkiebell guys, please check it out. The description. Does it make sense? Did I miss something (no a pro with monorepos yet)?

**Comment by troggy** [comment]
Feel free to change the description, if needed 🙏

**Comment by pinkiebell** [comment]
Nice one 🎉 . Are we fine with a directory structure like this, or do we want different setup ?
So basically we have the same structure in the beginning and we can change later iteratively if we want to merge specific stuff completely together.
```
<leap-node>
  - contracts
     - same like leap-contracts
  - node
    - same like leap-node
  - test
     - includes the integrations tests. Refactored to run with the new monorepo
```

**Comment by troggy** [comment]
the root name shouldn't be `leap-node`, but rather the network name (we are still deciding on the name ^^)

**Comment by sunify** [comment]
`leapdao-stuff`

**Comment by troggy** [comment]
obsolete
