### ISSUE TITLE
Press Release & Press Outeach | Cannes Film Festival Project 

### ISSUE THREAD

**Issue by kohola71** [leapdao/meta#97]
# Bounty
Write the press release and carry out press outreach around the Cannes Film Festival project to get LeapDAO featured alongside White Rabbit and Cinemarket. 

## Scope
As per doc: https://docs.google.com/document/d/1QS4goTOE8TdeNaXoUzk8FKeKDx_BE0zC2ru6Qvzr108/edit#

## Deliverables
- press release copy
- press outreach to tech and film industry publications
- main contact for press outreach

## Gain for the project
Exposure for LeapDAO in a real life use case / exposure in tech press and beyond

## Roles
bounty gardener: @kohola71 / 10%
bounty worker: @kohola71 / 80%
bounty reviewer: @johannbarbie  / 10% 

S 350

**Comment by johannbarbie** [comment]
delivered and payed out
