### ISSUE TITLE
swag for leapDAO / solEVM (pair programming)

### ISSUE THREAD

**Issue by johannbarbie** [leapdao/meta#98]
# Bounty
stickers / t-shirts / socks / hats / coins / other for leapDAO / solEVM

## Gain for the project
- help people to remember us
- earn money with mearch

## Deliverables
- easy to use online shop that works with (BTC, ETH & DAI)
- Mearch products with a print on demand system
- Earnings go to the multi sig (connection to it)
- Design for the Mearch products
- Bounty should cover set ups cost

## Roles
bounty gardener: @johannbarbie  / 10%
bounty worker: @simonweniger  / 80%
bounty reviewer: name / 10%

**Comment by troggy** [comment]
![image](https://user-images.githubusercontent.com/163447/61952667-1ce59b00-afbd-11e9-9d55-fae40c9aebfc.png)

https://www.aliexpress.com/item/32974360426.html 😎

**Comment by TimDaub** [comment]
Since we're preaching sustainability with Planet A and since it'd be nice to have tshirts to give away at EthBerlin, how about the following idea:

**Comment by johannbarbie** [comment]
paid out here: https://leapdao.slack.com/archives/C75C00YJD/p1575325119002300
